In [397]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [398]:
df=pd.read_csv('laptop_dataset_final.csv')

C:\Users\shiva\AppData\Local\Temp\ipykernel_21628\4152467657.py:1: DtypeWarning: Columns (0: Chipset, 1: RAM Speed, 2: Memory Slots, 3: SSD Type, 4: HDMI Ports, 5: Audio Solution, 6: Brightness, 7: Expandable Memory, 8: Thunderbolt Port, 9: VGA Port, 10: HDD Capacity, 11: HDD Speed(RPM), 12: HDD Type, 13: Lockport, 14: Battery Capacity, 15: Aspect Ratio, 16: SSD Interface, 17: Fast Charging Support) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('laptop_dataset_final.csv')

In [399]:
df.sample(5)

,Brand,Model,Series,Thickness,Dimensions (WxDxH),Weight,Colors,Operating System,Operating System Type,Display Size,...,Lockport,Battery Life,USB Type C,Battery Capacity,Aspect Ratio,Number of Cores,SSD Interface,Fast Charging Support,market_status,Price (Rs)
6576,Dell,3525 (D560863WIN9B),Inspiron 15,21 Millimeter thickness,358 x 235 x 21 mm,1.68 Kg weight,Carbon Black,Windows 11 Home Basic,64-bit,15.6 Inches (39.62 cm),...,NaN,7 Hrs,1.0,NaN,NaN,NaN,NaN,NaN,Available,62929.0
3761,Lenovo,E16 G1 (21JNS03P00),Thinkpad,20 Millimeter thickness,356 x 248 x 20 mm,1.77 Kg weight,Black,Windows 11 Home Basic,64-bit,16 Inches (40.64 cm),...,NaN,NaN,1.0,57 WHrs,NaN,6.0,NaN,NaN,Out of Stock,49190.0
4557,Lenovo,V130 (81HNA01AIH),NaN,22.3 Millimeter thickness,375 x 253 x 22.3 mm,1.8 Kg weight,Grey,DOS,NaN,15.6 Inches (39.62 cm),...,No,6 Hrs,NaN,NaN,NaN,NaN,NaN,NaN,Out of Stock,23400.0
5975,Lenovo,S145 (81VD00EFIN),Ideapad,19.9 Millimeter thickness,362.2 x 251.5 x 19.9 mm,1.85 Kg weight,Grey,Windows 10 Home Basic,64-bit,15.6 Inches (39.62 cm),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Available,30990.0
5675,Razer,RZ09-01963E31-R3U1,Blade Stealth,13.1 Millimeter thickness (Slim),321 x 206 x 13.1 mm,1.33 Kg weight (Light-weight),Black,Windows 10 Professional,64-bit,13.3 Inches (33.78 cm),...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Out of Stock,265125.0

In [400]:
df.shape

(8198, 76)

In [401]:
df.columns

Index(['Brand', 'Model', 'Series', 'Thickness', 'Dimensions (WxDxH)', 'Weight',
       'Colors', 'Operating System', 'Operating System Type', 'Display Size',
       'Display Resolution', 'Pixel Density', 'Display Type',
       'Display Features', 'Display Touchscreen', 'Processor', 'Clock-speed',
       'Chipset', 'Cache', 'Graphic Processor', 'Capacity', 'RAM Type',
       'RAM Speed', 'Memory Slots', 'Memory Layout', 'SSD Capacity',
       'SSD Type', 'Battery Cell', 'Battery Type', 'Power Supply',
       'Wireless LAN', 'Wi-Fi Version', 'Bluetooth', 'Bluetooth Version',
       'Other Networking Options', 'HDMI Ports', 'USB 2.0 slots',
       'SD Card Reader', 'Ethernet ports', 'Headphone Jack', 'Microphone Jack',
       'Web-cam', 'Video Recording', 'Audio Solution', 'Speakers',
       'Sound Technologies', 'In-built Microphone', 'Microphone Type',
       'Pointing device', 'Keyboard', 'Fingerprint scanner',
       'Face Recognition', 'Warranty', 'Sales Package', 'Refresh Rate',
       'Brightness', 'Graphics Memory', 'Expandable Memory',
       'Thunderbolt Port', 'VGA Port', 'Backlit Keyboard', 'HDD Capacity',
       'HDD Speed(RPM)', 'HDD Type', 'USB 3.0 slots',
       'Secondary cam(Rear-facing)', 'Lockport', 'Battery Life', 'USB Type C',
       'Battery Capacity', 'Aspect Ratio', 'Number of Cores', 'SSD Interface',
       'Fast Charging Support', 'market_status', 'Price (Rs)'],
      dtype='str')

In [402]:
pd.set_option('display.max_rows', None)

print(df.isnull().sum())

Brand                            0
Model                            0
Series                        1093
Thickness                      680
Dimensions (WxDxH)             682
Weight                         307
Colors                         176
Operating System                 0
Operating System Type         3520
Display Size                     3
Display Resolution              32
Pixel Density                   34
Display Type                  3890
Display Features               132
Display Touchscreen             82
Processor                        0
Clock-speed                    471
Chipset                       7147
Cache                         1571
Graphic Processor               92
Capacity                         0
RAM Type                       170
RAM Speed                     3093
Memory Slots                    64
Memory Layout                  156
SSD Capacity                  1334
SSD Type                      5744
Battery Cell                  1306
Battery Type                   737
Power Supply                  1417
Wireless LAN                    74
Wi-Fi Version                   74
Bluetooth                       49
Bluetooth Version              818
Other Networking Options      5660
HDMI Ports                     757
USB 2.0 slots                 4973
SD Card Reader                3712
Ethernet ports                4754
Headphone Jack                  14
Microphone Jack                 17
Web-cam                        275
Video Recording               1156
Audio Solution                5562
Speakers                       109
Sound Technologies            4565
In-built Microphone            188
Microphone Type                238
Pointing device               2320
Keyboard                      1078
Fingerprint scanner           2688
Face Recognition              5666
Warranty                       458
Sales Package                   14
Refresh Rate                  5079
Brightness                    5826
Graphics Memory               5121
Expandable Memory             4963
Thunderbolt Port              7205
VGA Port                      4349
Backlit Keyboard              3597
HDD Capacity                  6344
HDD Speed(RPM)                6462
HDD Type                      6469
USB 3.0 slots                 5975
Secondary cam(Rear-facing)    4966
Lockport                      6664
Battery Life                  5476
USB Type C                    3007
Battery Capacity              5744
Aspect Ratio                  6869
Number of Cores               5273
SSD Interface                 6145
Fast Charging Support         7258
market_status                    0
Price (Rs)                      21
dtype: int64

In [403]:
df.isnull().sum()

Brand                            0
Model                            0
Series                        1093
Thickness                      680
Dimensions (WxDxH)             682
Weight                         307
Colors                         176
Operating System                 0
Operating System Type         3520
Display Size                     3
Display Resolution              32
Pixel Density                   34
Display Type                  3890
Display Features               132
Display Touchscreen             82
Processor                        0
Clock-speed                    471
Chipset                       7147
Cache                         1571
Graphic Processor               92
Capacity                         0
RAM Type                       170
RAM Speed                     3093
Memory Slots                    64
Memory Layout                  156
SSD Capacity                  1334
SSD Type                      5744
Battery Cell                  1306
Battery Type                   737
Power Supply                  1417
Wireless LAN                    74
Wi-Fi Version                   74
Bluetooth                       49
Bluetooth Version              818
Other Networking Options      5660
HDMI Ports                     757
USB 2.0 slots                 4973
SD Card Reader                3712
Ethernet ports                4754
Headphone Jack                  14
Microphone Jack                 17
Web-cam                        275
Video Recording               1156
Audio Solution                5562
Speakers                       109
Sound Technologies            4565
In-built Microphone            188
Microphone Type                238
Pointing device               2320
Keyboard                      1078
Fingerprint scanner           2688
Face Recognition              5666
Warranty                       458
Sales Package                   14
Refresh Rate                  5079
Brightness                    5826
Graphics Memory               5121
Expandable Memory             4963
Thunderbolt Port              7205
VGA Port                      4349
Backlit Keyboard              3597
HDD Capacity                  6344
HDD Speed(RPM)                6462
HDD Type                      6469
USB 3.0 slots                 5975
Secondary cam(Rear-facing)    4966
Lockport                      6664
Battery Life                  5476
USB Type C                    3007
Battery Capacity              5744
Aspect Ratio                  6869
Number of Cores               5273
SSD Interface                 6145
Fast Charging Support         7258
market_status                    0
Price (Rs)                      21
dtype: int64

In [404]:
df= df.drop(['HDMI Ports','Bluetooth','Thickness','In-built Microphone','Headphone Jack', 'Microphone Jack',
             'Dimensions (WxDxH)','Microphone Type','Bluetooth Version','Battery Cell','Memory Layout','Memory Slots',
             'Display Features','Colors','Wireless LAN','Power Supply','Web-cam','Speakers', 'Series','Audio Solution','Sound Technologies' ,'Video Recording','Operating System Type','Refresh Rate',
       'Brightness', 'Graphics Memory', 'Expandable Memory','Ethernet ports','SD Card Reader',
       'Thunderbolt Port', 'VGA Port', 'Backlit Keyboard', 'HDD Capacity','SSD Type',
       'HDD Speed(RPM)', 'HDD Type', 'USB 3.0 slots','USB 2.0 slots','Other Networking Options',
       'Secondary cam(Rear-facing)', 'Lockport', 'Battery Life', 'USB Type C','RAM Speed',
       'Battery Capacity', 'Aspect Ratio', 'Number of Cores', 'SSD Interface','Chipset',
       'Fast Charging Support','Pointing device','Keyboard' ,  'Fingerprint scanner', 
       'Face Recognition','Display Type' ,'Operating System Type','Cache','Sales Package', 'market_status'],axis=1)

In [405]:
df.duplicated().sum()

np.int64(2)

In [406]:
df=df.drop_duplicates()

In [407]:
df.columns

Index(['Brand', 'Model', 'Weight', 'Operating System', 'Display Size',
       'Display Resolution', 'Pixel Density', 'Display Touchscreen',
       'Processor', 'Clock-speed', 'Graphic Processor', 'Capacity', 'RAM Type',
       'SSD Capacity', 'Battery Type', 'Wi-Fi Version', 'Warranty',
       'Price (Rs)'],
      dtype='str')

In [408]:
df.isnull().sum()

Brand                     0
Model                     0
Weight                  307
Operating System          0
Display Size              3
Display Resolution       32
Pixel Density            34
Display Touchscreen      82
Processor                 0
Clock-speed             471
Graphic Processor        92
Capacity                  0
RAM Type                170
SSD Capacity           1334
Battery Type            736
Wi-Fi Version            74
Warranty                458
Price (Rs)               21
dtype: int64

- brand

In [409]:
df['Brand'].unique()

<StringArray>
[       'HP',      'Acer',      'Dell',       'MSI',    'Lenovo',     'iBall',
      'Asus',     'Avita',    'realme',     'Apple',   'Infinix',   'Samsung',
     'Honor',   'Thomson', 'Primebook',    'Xiaomi',  'Micromax',     'Tecno',
 'Zebronics',      'VAIO', 'Microsoft',        'LG',  'Gigabyte',  'Reliance',
     'Wings',       'RDP',     'Nokia',   'Fujitsu',  'Coconics',    'Huawei',
  'Motorola',      'Lava',  'Smartron',     'Razer',  'Colorful']
Length: 35, dtype: str

In [410]:
df['Brand'].value_counts()

Brand
Asus         1971
Lenovo       1748
HP           1629
Dell          862
Acer          822
MSI           526
Apple         186
Samsung        99
Microsoft      73
Infinix        67
Avita          33
Gigabyte       29
LG             28
Honor          16
Fujitsu        15
iBall          12
Xiaomi         11
Thomson         8
Zebronics       8
Razer           6
Huawei          5
Motorola        5
Colorful        5
Wings           4
Nokia           4
Coconics        4
realme          3
Micromax        3
Tecno           3
VAIO            3
Primebook       2
Reliance        2
Smartron        2
RDP             1
Lava            1
Name: count, dtype: int64

- Weight

In [411]:
df['Weight'] = df['Weight'].str.extract(r'(\d+\.?\d*)').astype(float)

In [412]:
df['Weight'].describe()

count    7889.000000
mean        1.825406
std         0.447908
min         0.510000
25%         1.500000
50%         1.750000
75%         2.190000
max         5.500000
Name: Weight, dtype: float64

In [413]:
df['Weight']

0       1.41
1       2.60
2       2.20
3       2.20
4       1.80
5       1.70
6       1.85
7       1.30
8       1.45
9       1.25
10      1.65
11      1.50
12      2.10
13      2.62
14      2.50
15      1.19
16      2.20
17      1.80
18      1.66
19      2.35
20      1.60
21      2.35
22      1.80
23      1.40
24      2.70
25      1.14
26      1.86
27      2.46
28      2.23
29      2.20
30      2.25
31      1.85
32      1.86
33      2.30
34      0.97
35      1.46
36      1.90
37      1.86
38      1.83
39      1.30
40      1.50
41      1.86
42      1.80
43      2.60
44      1.30
45      1.70
46      1.37
47      2.20
48      1.85
49      1.86
50      2.50
51      1.80
52      1.60
53      1.65
54      1.75
55      1.98
56      2.30
57      1.24
58      1.80
59      2.33
60      1.50
61      1.86
62      2.70
63      1.30
64      2.20
65      1.70
66      1.24
67      1.90
68      1.70
69      0.98
70      1.57
71      1.90
72      1.77
73      1.60
74      2.20
75      1.75
76      2.60
77      1.63
78      1.85
79      1.85
80      2.19
81      1.70
82      1.56
83      2.00
84       NaN
85      1.32
86      2.20
87      1.41
88      1.50
89      2.20
90      2.10
91      1.32
92      2.10
93      1.70
94      1.41
95      2.30
96      1.77
97      1.86
98      1.58
99      2.20
100     2.40
101     2.10
102     1.40
103     1.41
104     2.30
105     2.10
106     1.86
107     2.30
108     1.20
109     1.30
110     1.30
111     1.85
112     1.78
113     1.80
114     2.25
115     1.85
116     2.20
117     1.80
118     1.70
119     1.46
120     1.50
121     1.00
122     1.40
123     1.85
124     1.30
125     1.69
126     2.60
127     2.30
128     2.30
129     2.25
130     1.69
131     1.60
132     1.80
133     1.86
134     2.20
135     1.69
136     1.70
137     2.00
138     1.70
139     1.59
140     1.77
141     2.20
142     1.41
143     1.50
144      NaN
145     1.69
146     1.40
147     1.11
148     2.25
149     1.50
150     1.48
151     1.90
152     1.40
153     1.40
154     1.11
155     1.80
156     2.10
157     1.98
158     2.10
159     1.47
160     2.40
161     2.20
162     2.20
163     1.47
164     1.70
165     2.22
166     1.69
167     2.20
168     1.72
169     1.80
170     2.20
171     1.58
172     1.25
173     1.25
174     2.32
175     1.75
176     1.86
177     1.38
178     1.65
179     2.20
180     1.25
181     2.10
182     1.40
183     1.40
184     1.50
185     2.20
186     1.38
187     2.20
188     1.60
189     1.83
190     1.48
191     1.46
192     1.70
193     1.54
194     2.48
195     1.41
196     2.36
197     1.25
198     1.70
199     1.68
200     1.90
201     1.40
202     1.70
203     1.39
204     2.30
205     2.30
206     1.55
207     2.25
208     1.41
209     1.20
210     2.40
211     2.10
212     2.19
213     2.30
214     1.80
215     1.12
216     2.19
217     2.30
218     2.30
219     2.40
220     2.40
221     2.50
222     2.60
223     1.88
224     1.47
225     2.10
226     2.30
227     2.46
228     1.63
229     2.30
230     1.85
231     2.40
232     1.45
233     2.32
234     2.19
235     2.50
236     2.00
237     2.30
238     2.30
239     1.50
240     2.20
241     1.70
242     1.23
243     1.80
244     2.57
245     1.80
246     2.80
247     2.60
248     2.30
249     2.20
250     2.30
251     2.81
252     1.70
253     2.40
254     2.20
255     1.50
256     1.98
257     2.10
258     2.20
259     1.65
260     2.40
261     2.03
262     2.20
263     1.74
264     1.80
265     1.70
266     1.86
267     2.30
268     2.30
269     1.70
270     1.88
271     1.38
272     1.20
273     1.34
274     1.17
275     3.21
276     2.30
277     1.55
278     1.30
279     1.77
280     1.80
281     2.30
282     1.40
283     0.60
284     2.30
285     2.30
286     1.34
287     1.88
288     2.30
289     2.25
290     1.62
291     2.38
292     3.30
293     1.47
294     1.68
295     1.70
296     1.60
297     2.60
298     2.10
299     1.89
300     1.70
301     1.25
302     1.80
303     1.29
304     2.40
305     1.34
306     1.80
307     1.30
308     1.59
309     2.30
310     2.30
311     2.20
312     2.20
313     1.90
314     2.30
315     2.30
316     1.70
317     2.20
318     2.48
319     2.99
320     1.60
321     2.30
322     1.90
323      NaN
324     1.79
325     1.30
326     2.26
327     2.30
328     1.90
329     2.30
330     1.65
331     2.50
332     2.34
333     2.30
334     1.88
335     1.60
336     1.85
337     1.34
338     2.80
339     2.25
340     1.87
341     2.40
342     1.46
343     1.53
344     2.30
345     1.60
346     2.10
347     1.60
348     1.70
349     2.10
350     4.04
351     1.17
352     2.60
353     1.00
354     1.50
355     1.30
356     1.60
357     1.38
358     1.78
359     1.77
360     2.50
361     2.85
362     2.99
363     1.19
364     2.25
365     1.45
366     1.35
367     1.39
368     1.92
369     2.30
370     1.70
371     2.30
372     2.10
373     2.20
374     1.90
375     2.10
376     2.38
377     1.62
378     1.38
379     1.30
380     1.62
381     1.18
382     1.15
383     1.62
384     1.39
385     1.62
386     1.19
387     1.39
388     1.88
389     1.39
390     1.60
391     1.72
392     1.00
393      NaN
394     1.88
395     1.79
396     1.38
397     1.38
398     1.62
399     1.34
400     1.46
401     1.75
402     1.77
403     1.24
404     1.80
405     2.10
406     1.85
407     1.83
408     1.75
409     1.60
410     2.10
411     1.70
412     2.20
413     1.86
414     1.25
415     1.96
416     1.41
417     1.70
418     1.58
419     1.80
420     1.74
421     1.60
422     2.50
423     2.20
424     1.40
425     1.40
426     2.30
427     1.49
428     1.80
429     1.49
430     1.40
431     2.30
432     1.86
433     1.86
434     2.30
435     1.70
436     2.30
437     1.85
438     2.40
439     1.24
440     2.29
441     1.47
442     1.63
443     1.49
444     2.62
445     1.69
446     2.00
447     2.60
448     2.00
449     2.10
450     1.46
451     1.80
452     2.20
453     1.09
454     1.58
455     1.49
456     1.43
457     1.30
458     1.74
459     1.70
460     1.41
461     1.80
462     2.20
463     1.86
464     1.25
465     1.85
466     1.85
467     1.40
468     1.25
469     1.86
470     1.40
471     1.40
472     1.35
473     2.40
474     1.60
475     1.63
476     2.10
477      NaN
478     1.77
479     2.10
480     1.34
481     2.20
482      NaN
483     2.30
484     2.30
485     1.69
486     1.70
487     1.63
488     1.86
489     1.80
490     1.25
491     1.40
492     2.30
493     2.60
494     1.57
495     1.57
496     1.83
497     2.00
498     2.10
499     2.30
500     2.00
501     1.86
502     1.30
503     1.69
504     1.86
505     1.59
506     2.30
507     1.98
508     1.77
509     2.20
510     1.25
511     2.20
512     1.80
513     1.74
514     1.70
515     1.75
516     0.98
517     2.30
518     1.25
519     2.30
520     1.20
521     2.19
522     1.77
523     1.47
524     0.90
525     1.77
526     1.60
527     1.83
528     1.50
529     2.37
530     1.12
531     1.50
532     1.60
533     0.98
534     1.86
535     2.50
536      NaN
537     1.30
538     2.70
539     2.20
540     1.80
541     2.33
542     1.70
543     2.10
544     1.40
545     1.50
546     1.40
547     2.70
548     1.40
549     1.20
550     2.14
551     1.85
552     1.85
553     2.20
554     1.86
555     1.70
556     2.30
557     2.25
558     2.25
559     1.30
560     1.92
561     2.20
562     1.82
563     1.80
564     1.86
565     1.46
566     1.77
567     2.30
568     1.65
569     1.80
570     1.41
571     1.80
572     1.83
573     2.30
574      NaN
575     1.75
576     1.86
577     1.47
578     2.48
579     2.20
580     1.65
581     1.24
582     2.46
583     1.90
584     2.20
585     1.90
586     1.41
587     1.65
588     2.60
589     2.60
590     1.69
591     1.69
592     1.41
593     2.60
594     1.50
595     1.90
596     1.34
597     2.20
598     1.80
599     1.80
600     1.38
601     1.57
602     1.43
603     1.70
604     1.19
605     2.68
606     1.70
607     1.77
608     1.62
609      NaN
610     1.39
611     2.29
612     1.19
613     1.40
614     1.19
615     2.80
616     1.39
617      NaN
618     1.40
619      NaN
620      NaN
621     1.59
622     1.59
623      NaN
624      NaN
625      NaN
626     2.29
627      NaN
628      NaN
629      NaN
630     1.85
631     1.39
632     1.49
633     1.55
634     1.77
635     2.50
636     1.49
637      NaN
638     1.70
639      NaN
640     3.60
641     2.20
642      NaN
643     1.51
644     1.35
645      NaN
646      NaN
647      NaN
648      NaN
649      NaN
650      NaN
651      NaN
652      NaN
653     1.85
654      NaN
655      NaN
656      NaN
657     1.44
658      NaN
659      NaN
660     1.49
661      NaN
662      NaN
663     1.45
664      NaN
665     1.62
666     2.29
667     1.86
668      NaN
669      NaN
670      NaN
671     1.49
672     1.00
673     1.18
674     1.40
675     1.40
676     1.50
677     1.61
678      NaN
679     2.38
680     1.48
681     1.59
682      NaN
683     2.50
684     1.59
685     2.30
686     2.36
687     1.79
688     1.73
689     1.73
690     1.98
691     1.73
692     1.73
693     1.73
694     1.73
695     1.73
696     1.73
697     1.73
698      NaN
699      NaN
700     2.38
701      NaN
702      NaN
703      NaN
704      NaN
705     1.18
706      NaN
707     1.38
708     2.38
709     1.55
710     1.38
711     1.61
712      NaN
713     2.36
714     2.24
715     2.38
716     1.31
717     1.50
718     1.31
719     0.99
720     1.76
721     1.41
722     0.99
723      NaN
724     1.59
725     1.62
726     1.60
727      NaN
728     1.60
729     1.62
730     1.82
731     1.82
732      NaN
733     1.48
734     1.46
735     2.39
736      NaN
737      NaN
738     2.45
739     1.80
740     2.22
741     1.86
742     1.39
743     2.00
744     1.70
745      NaN
746      NaN
747     2.29
748     1.24
749     1.49
750     1.78
751      NaN
752     2.29
753      NaN
754      NaN
755     1.32
756     2.29
757     1.63
758     1.51
759     1.60
760     2.33
761     2.39
762     2.39
763     1.30
764      NaN
765      NaN
766     1.59
767     1.59
768     1.54
769     1.50
770     2.10
771     1.41
772     1.74
773      NaN
774     1.59
775      NaN
776      NaN
777      NaN
778     1.59
779     1.59
780     1.32
781     1.63
782     1.62
783     1.59
784     1.49
785      NaN
786     1.59
787     1.86
788      NaN
789     1.86
790     1.62
791     1.45
792     1.86
793     1.94
794      NaN
795      NaN
796     1.37
797     1.58
798      NaN
799     1.80
800     2.20
801     1.75
802     1.77
803     2.35
804     2.20
805     1.75
806     1.76
807     1.55
808     1.76
809     1.70
810     1.41
811     2.15
812     1.40
813     1.40
814     1.70
815     2.10
816     1.86
817     1.40
818     2.00
819     2.30
820     1.69
821     1.77
822     1.69
823     1.80
824     1.77
825     1.69
826     1.90
827     1.59
828     1.77
829     1.80
830     1.74
831     2.20
832     1.65
833     2.10
834     1.90
835     1.90
836     1.80
837     1.69
838     1.79
839     1.40
840     1.69
841     1.98
842     0.99
843     1.77
844     2.00
845     2.10
846     1.86
847     1.77
848     1.47
849     2.00
850     1.77
851     1.06
852     1.20
853     2.19
854     1.60
855     1.40
856     1.80
857     2.20
858     1.74
859     1.46
860     1.86
861     1.47
862     1.70
863     2.10
864     2.60
865     1.98
866     2.50
867     2.10
868     1.41
869     1.50
870     1.41
871     1.79
872     2.20
873     1.70
874     1.79
875     2.20
876     1.80
877     1.80
878     1.69
879     1.86
880     2.10
881     2.00
882     1.75
883     2.20
884     1.41
885     2.20
886     1.70
887     1.25
888     1.86
889     2.40
890     2.20
891     1.80
892     2.20
893     1.41
894     1.85
895     2.10
896     1.70
897     1.63
898     1.41
899     2.37
900     2.40
901     1.41
902     1.85
903     1.85
904     1.50
905     1.85
906     1.47
907     1.74
908     1.70
909     1.58
910     1.69
911     1.46
912     1.69
913     1.46
914     1.14
915     2.14
916     2.20
917     2.30
918     1.58
919     1.63
920     1.07
921     1.07
922     1.69
923     2.18
924     1.55
925     1.63
926     1.24
927     2.19
928     2.60
929     1.78
930     1.70
931     2.40
932     1.77
933     1.47
934     1.06
935     1.41
936     1.80
937     2.30
938     1.40
939     1.70
940     2.19
941     2.40
942     2.19
943     2.53
944     2.48
945     1.70
946     1.77
947     1.13
948     1.50
949     1.41
950     1.78
951     1.30
952     1.48
953     2.10
954     2.30
955     1.48
956     1.47
957     2.10
958     2.10
959     2.20
960     1.61
961     1.69
962     2.10
963     1.75
964     1.80
965     2.15
966     2.00
967     2.10
968     1.60
969     1.70
970     1.80
971     1.85
972     2.10
973     1.65
974     1.83
975     1.85
976     1.80
977     2.10
978     1.66
979     1.58
980     1.98
981     2.30
982     1.65
983     2.19
984     2.10
985     1.69
986     1.68
987     1.40
988     2.70
989     2.04
990     1.86
991     2.37
992     1.55
993     1.58
994     1.86
995     1.37
996     1.69
997     2.35
998     1.75
999     1.10
1000    1.59
1001     NaN
1002    1.47
1003    2.35
1004    2.12
1005    1.12
1006    2.29
1007    2.30
1008    1.78
1009     NaN
1010     NaN
1011    1.40
1012     NaN
1013    1.24
1014    2.81
1015    2.81
1016     NaN
1017    2.81
1018    2.81
1019    2.81
1020     NaN
1021     NaN
1022     NaN
1023     NaN
1024    1.37
1025     NaN
1026     NaN
1027     NaN
1028    1.36
1029    1.55
1030     NaN
1031    1.52
1032    2.38
1033     NaN
1034     NaN
1035     NaN
1036    1.74
1037    1.38
1038    1.38
1039     NaN
1040    1.79
1041     NaN
1042    1.38
1043     NaN
1044    1.19
1045    1.36
1046    1.79
1047    1.36
1048    1.36
1049    1.59
1050    1.47
1051    1.39
1052    1.47
1053    1.47
1054    1.59
1055    1.47
1056    1.39
1057    1.56
1058    1.44
1059    1.44
1060    1.56
1061    1.75
1062    2.29
1063    1.38
1064    2.29
1065    1.39
1066    2.29
1067    1.20
1068    1.70
1069    1.65
1070     NaN
1071    1.59
1072    1.50
1073    2.10
1074    1.50
1075    2.50
1076    1.50
1077    1.59
1078    1.59
1079    1.88
1080     NaN
1081    1.69
1082    2.50
1083     NaN
1084    1.55
1085     NaN
1086    2.29
1087    1.32
1088    2.20
1089    1.45
1090    2.29
1091    1.99
1092    1.83
1093    2.29
1094    2.29
1095    2.29
1096    1.40
1097    1.40
1098    2.40
1099    1.86
1100    2.10
1101    1.59
1102    2.40
1103    2.80
1104    1.74
1105    2.99
1106    1.47
1107    1.38
1108     NaN
1109    1.38
1110    1.38
1111    1.38
1112    1.36
1113     NaN
1114    1.36
1115    1.30
1116    0.99
1117    1.38
1118    1.38
1119    1.37
1120     NaN
1121    1.38
1122     NaN
1123    1.38
1124    1.74
1125    1.74
1126    1.74
1127    1.37
1128    1.50
1129    1.38
1130    1.74
1131    1.47
1132    1.38
1133    2.29
1134    2.12
1135     NaN
1136    2.12
1137    2.12
1138    2.12
1139    2.12
1140    2.12
1141    2.12
1142    1.56
1143    2.29
1144    1.51
1145    1.66
1146    1.80
1147    1.56
1148    1.75
1149    1.66
1150    1.80
1151    1.56
1152    1.56
1153    1.78
1154    1.56
1155    1.37
1156    1.99
1157    1.78
1158    1.54
1159    1.76
1160    2.81
1161    2.81
1162    1.81
1163    1.54
1164    1.45
1165    1.15
1166     NaN
1167    1.39
1168    1.39
1169    1.38
1170    1.40
1171    1.23
1172    1.33
1173    1.15
1174    1.15
1175    2.40
1176    1.30
1177    1.62
1178    1.70
1179    1.59
1180    1.30
1181    3.60
1182    2.89
1183    3.60
1184    1.28
1185    1.99
1186    1.99
1187    1.34
1188    1.78
1189    1.35
1190    2.10
1191    1.35
1192    1.34
1193    1.39
1194    1.40
1195    1.38
1196    1.28
1197    1.34
1198    1.56
1199    1.65
1200    1.00
1201    1.38
1202    2.20
1203    2.36
1204    2.30
1205    1.66
1206    1.38
1207    1.29
1208    2.31
1209    1.25
1210    1.11
1211    1.56
1212    1.85
1213    1.50
1214    1.75
1215    1.70
1216    2.03
1217    1.46
1218    1.65
1219    2.19
1220    2.40
1221    2.37
1222    1.59
1223    1.39
1224    2.37
1225    1.50
1226    1.59
1227    1.50
1228    2.30
1229    2.20
1230    2.10
1231    1.80
1232    2.70
1233    1.67
1234    2.60
1235    1.70
1236    2.25
1237    2.37
1238    2.37
1239    2.20
1240    2.25
1241    2.48
1242    1.70
1243    2.37
1244    1.60
1245    1.35
1246    1.80
1247    2.20
1248    2.20
1249    1.60
1250    1.60
1251    2.37
1252    2.37
1253    1.58
1254    2.10
1255    1.25
1256    1.30
1257    2.60
1258    1.75
1259    1.60
1260    1.60
1261    1.41
1262    1.47
1263    2.48
1264    1.40
1265    1.77
1266    1.50
1267    1.25
1268    2.40
1269    1.47
1270    1.75
1271    1.61
1272    1.50
1273    1.30
1274    1.83
1275    1.83
1276    1.83
1277     NaN
1278    1.69
1279    1.47
1280    1.69
1281    2.20
1282    2.00
1283    2.25
1284    1.48
1285    1.48
1286    1.68
1287    1.52
1288    1.32
1289    1.79
1290    1.38
1291    1.76
1292    1.60
1293    1.68
1294    1.69
1295    1.40
1296    1.37
1297    2.50
1298    2.20
1299    1.51
1300    1.61
1301    1.13
1302    1.25
1303    1.76
1304    1.74
1305    1.40
1306    2.20
1307    1.40
1308    1.90
1309    1.75
1310    1.60
1311    1.80
1312    1.80
1313    1.75
1314    1.74
1315    1.80
1316    2.44
1317    1.70
1318    1.83
1319    1.25
1320    2.70
1321    1.78
1322    1.80
1323    1.74
1324    2.30
1325    2.30
1326    1.83
1327    2.30
1328    2.25
1329     NaN
1330    1.86
1331    1.80
1332    1.43
1333    1.77
1334    2.57
1335    1.90
1336    2.25
1337    1.90
1338    1.40
1339    1.88
1340    2.50
1341    1.18
1342    1.83
1343    1.59
1344    1.77
1345    0.79
1346    2.50
1347    1.90
1348    1.50
1349    2.32
1350    2.10
1351    1.46
1352    1.77
1353    1.38
1354    1.40
1355    2.32
1356    2.60
1357    1.38
1358    2.32
1359    2.20
1360    2.20
1361    1.50
1362    2.20
1363    1.40
1364    1.86
1365    1.52
1366    1.51
1367    2.10
1368    1.51
1369    1.80
1370    1.51
1371    2.40
1372    1.40
1373    1.51
1374    1.72
1375    1.80
1376    2.25
1377    1.56
1378    1.51
1379    1.51
1380    2.46
1381    1.46
1382    1.17
1383    2.30
1384    1.41
1385    2.25
1386    2.20
1387    1.66
1388    1.80
1389    1.80
1390    2.00
1391    1.70
1392    1.83
1393    2.25
1394    2.93
1395    1.80
1396    2.30
1397    2.10
1398    1.10
1399    2.00
1400    1.90
1401    2.14
1402    1.85
1403    2.03
1404    1.92
1405    1.27
1406    1.40
1407    2.36
1408    2.20
1409    2.20
1410    1.40
1411    2.30
1412    1.60
1413    1.79
1414    2.00
1415    2.40
1416    1.63
1417    2.40
1418    2.38
1419    1.60
1420    1.70
1421    2.20
1422    1.35
1423    1.35
1424    2.20
1425    2.10
1426    2.18
1427    1.35
1428    1.90
1429    1.55
1430    1.60
1431    2.24
1432    1.83
1433     NaN
1434    2.20
1435    1.70
1436    1.85
1437    1.83
1438    2.20
1439    1.90
1440    1.85
1441    1.41
1442    1.54
1443    2.30
1444    3.24
1445    1.80
1446    1.68
1447    2.36
1448    2.30
1449    1.40
1450    0.51
1451    1.85
1452    1.38
1453    1.22
1454    1.40
1455    1.77
1456    1.88
1457    1.55
1458    1.50
1459    1.40
1460    2.70
1461    1.22
1462    1.72
1463    2.25
1464    3.25
1465    2.80
1466    1.70
1467    1.90
1468    1.36
1469    1.39
1470    1.47
1471    2.46
1472    1.80
1473    1.60
1474    1.85
1475    1.60
1476    1.65
1477    1.40
1478    2.20
1479    1.25
1480    4.00
1481    1.32
1482    1.70
1483    2.34
1484    2.00
1485    1.50
1486    2.60
1487    1.55
1488    2.45
1489    1.80
1490    1.55
1491    1.48
1492    1.80
1493    1.60
1494    2.40
1495    2.30
1496    1.48
1497    1.46
1498    1.77
1499    1.42
1500    1.70
1501    2.00
1502    2.20
1503    2.10
1504    2.30
1505    1.31
1506    1.47
1507    2.20
1508    2.34
1509    1.52
1510    1.55
1511    2.30
1512    1.80
1513    1.15
1514    1.40
1515    1.50
1516    2.25
1517    2.80
1518    2.25
1519    2.10
1520    1.77
1521    2.60
1522    1.86
1523    1.29
1524    2.20
1525    2.30
1526    3.00
1527    1.25
1528    1.70
1529    1.10
1530    1.70
1531    2.60
1532    1.85
1533     NaN
1534    2.10
1535    2.19
1536    1.47
1537    1.80

In [414]:
df['Weight'].mean()

np.float64(1.8254062618836355)

In [415]:
df['Weight'] = df['Weight'].fillna(df['Weight'].mean())

In [416]:
df['Display Size']=df['Display Size'].str.extract(r'(\d+\.?\d*)').astype(float)

In [417]:
def weight_category(w):
    if w <= 1.3:
        return 'Ultra Light'
    elif w <= 1.8:
        return 'Light'
    elif w <= 2.3:
        return 'Normal'
    else:
        return 'Heavy'

df['Weight_Category'] = df['Weight'].apply(weight_category)

In [418]:
df['Weight_Category']

0             Light
1             Heavy
2            Normal
3            Normal
4             Light
5             Light
6            Normal
7       Ultra Light
8             Light
9       Ultra Light
10            Light
11            Light
12           Normal
13            Heavy
14            Heavy
15      Ultra Light
16           Normal
17            Light
18            Light
19            Heavy
20            Light
21            Heavy
22            Light
23            Light
24            Heavy
25      Ultra Light
26           Normal
27            Heavy
28           Normal
29           Normal
30           Normal
31           Normal
32           Normal
33           Normal
34      Ultra Light
35            Light
36           Normal
37           Normal
38           Normal
39      Ultra Light
40            Light
41           Normal
42            Light
43            Heavy
44      Ultra Light
45            Light
46            Light
47           Normal
48           Normal
49           Normal
50            Heavy
51            Light
52            Light
53            Light
54            Light
55           Normal
56           Normal
57      Ultra Light
58            Light
59            Heavy
60            Light
61           Normal
62            Heavy
63      Ultra Light
64           Normal
65            Light
66      Ultra Light
67           Normal
68            Light
69      Ultra Light
70            Light
71           Normal
72            Light
73            Light
74           Normal
75            Light
76            Heavy
77            Light
78           Normal
79           Normal
80           Normal
81            Light
82            Light
83           Normal
84           Normal
85            Light
86           Normal
87            Light
88            Light
89           Normal
90           Normal
91            Light
92           Normal
93            Light
94            Light
95           Normal
96            Light
97           Normal
98            Light
99           Normal
100           Heavy
101          Normal
102           Light
103           Light
104          Normal
105          Normal
106          Normal
107          Normal
108     Ultra Light
109     Ultra Light
110     Ultra Light
111          Normal
112           Light
113           Light
114          Normal
115          Normal
116          Normal
117           Light
118           Light
119           Light
120           Light
121     Ultra Light
122           Light
123          Normal
124     Ultra Light
125           Light
126           Heavy
127          Normal
128          Normal
129          Normal
130           Light
131           Light
132           Light
133          Normal
134          Normal
135           Light
136           Light
137          Normal
138           Light
139           Light
140           Light
141          Normal
142           Light
143           Light
144          Normal
145           Light
146           Light
147     Ultra Light
148          Normal
149           Light
150           Light
151          Normal
152           Light
153           Light
154     Ultra Light
155           Light
156          Normal
157          Normal
158          Normal
159           Light
160           Heavy
161          Normal
162          Normal
163           Light
164           Light
165          Normal
166           Light
167          Normal
168           Light
169           Light
170          Normal
171           Light
172     Ultra Light
173     Ultra Light
174           Heavy
175           Light
176          Normal
177           Light
178           Light
179          Normal
180     Ultra Light
181          Normal
182           Light
183           Light
184           Light
185          Normal
186           Light
187          Normal
188           Light
189          Normal
190           Light
191           Light
192           Light
193           Light
194           Heavy
195           Light
196           Heavy
197     Ultra Light
198           Light
199           Light
200          Normal
201           Light
202           Light
203           Light
204          Normal
205          Normal
206           Light
207          Normal
208           Light
209     Ultra Light
210           Heavy
211          Normal
212          Normal
213          Normal
214           Light
215     Ultra Light
216          Normal
217          Normal
218          Normal
219           Heavy
220           Heavy
221           Heavy
222           Heavy
223          Normal
224           Light
225          Normal
226          Normal
227           Heavy
228           Light
229          Normal
230          Normal
231           Heavy
232           Light
233           Heavy
234          Normal
235           Heavy
236          Normal
237          Normal
238          Normal
239           Light
240          Normal
241           Light
242     Ultra Light
243           Light
244           Heavy
245           Light
246           Heavy
247           Heavy
248          Normal
249          Normal
250          Normal
251           Heavy
252           Light
253           Heavy
254          Normal
255           Light
256          Normal
257          Normal
258          Normal
259           Light
260           Heavy
261          Normal
262          Normal
263           Light
264           Light
265           Light
266          Normal
267          Normal
268          Normal
269           Light
270          Normal
271           Light
272     Ultra Light
273           Light
274     Ultra Light
275           Heavy
276          Normal
277           Light
278     Ultra Light
279           Light
280           Light
281          Normal
282           Light
283     Ultra Light
284          Normal
285          Normal
286           Light
287          Normal
288          Normal
289          Normal
290           Light
291           Heavy
292           Heavy
293           Light
294           Light
295           Light
296           Light
297           Heavy
298          Normal
299          Normal
300           Light
301     Ultra Light
302           Light
303     Ultra Light
304           Heavy
305           Light
306           Light
307     Ultra Light
308           Light
309          Normal
310          Normal
311          Normal
312          Normal
313          Normal
314          Normal
315          Normal
316           Light
317          Normal
318           Heavy
319           Heavy
320           Light
321          Normal
322          Normal
323          Normal
324           Light
325     Ultra Light
326          Normal
327          Normal
328          Normal
329          Normal
330           Light
331           Heavy
332           Heavy
333          Normal
334          Normal
335           Light
336          Normal
337           Light
338           Heavy
339          Normal
340          Normal
341           Heavy
342           Light
343           Light
344          Normal
345           Light
346          Normal
347           Light
348           Light
349          Normal
350           Heavy
351     Ultra Light
352           Heavy
353     Ultra Light
354           Light
355     Ultra Light
356           Light
357           Light
358           Light
359           Light
360           Heavy
361           Heavy
362           Heavy
363     Ultra Light
364          Normal
365           Light
366           Light
367           Light
368          Normal
369          Normal
370           Light
371          Normal
372          Normal
373          Normal
374          Normal
375          Normal
376           Heavy
377           Light
378           Light
379     Ultra Light
380           Light
381     Ultra Light
382     Ultra Light
383           Light
384           Light
385           Light
386     Ultra Light
387           Light
388          Normal
389           Light
390           Light
391           Light
392     Ultra Light
393          Normal
394          Normal
395           Light
396           Light
397           Light
398           Light
399           Light
400           Light
401           Light
402           Light
403     Ultra Light
404           Light
405          Normal
406          Normal
407          Normal
408           Light
409           Light
410          Normal
411           Light
412          Normal
413          Normal
414     Ultra Light
415          Normal
416           Light
417           Light
418           Light
419           Light
420           Light
421           Light
422           Heavy
423          Normal
424           Light
425           Light
426          Normal
427           Light
428           Light
429           Light
430           Light
431          Normal
432          Normal
433          Normal
434          Normal
435           Light
436          Normal
437          Normal
438           Heavy
439     Ultra Light
440          Normal
441           Light
442           Light
443           Light
444           Heavy
445           Light
446          Normal
447           Heavy
448          Normal
449          Normal
450           Light
451           Light
452          Normal
453     Ultra Light
454           Light
455           Light
456           Light
457     Ultra Light
458           Light
459           Light
460           Light
461           Light
462          Normal
463          Normal
464     Ultra Light
465          Normal
466          Normal
467           Light
468     Ultra Light
469          Normal
470           Light
471           Light
472           Light
473           Heavy
474           Light
475           Light
476          Normal
477          Normal
478           Light
479          Normal
480           Light
481          Normal
482          Normal
483          Normal
484          Normal
485           Light
486           Light
487           Light
488          Normal
489           Light
490     Ultra Light
491           Light
492          Normal
493           Heavy
494           Light
495           Light
496          Normal
497          Normal
498          Normal
499          Normal
500          Normal
501          Normal
502     Ultra Light
503           Light
504          Normal
505           Light
506          Normal
507          Normal
508           Light
509          Normal
510     Ultra Light
511          Normal
512           Light
513           Light
514           Light
515           Light
516     Ultra Light
517          Normal
518     Ultra Light
519          Normal
520     Ultra Light
521          Normal
522           Light
523           Light
524     Ultra Light
525           Light
526           Light
527          Normal
528           Light
529           Heavy
530     Ultra Light
531           Light
532           Light
533     Ultra Light
534          Normal
535           Heavy
536          Normal
537     Ultra Light
538           Heavy
539          Normal
540           Light
541           Heavy
542           Light
543          Normal
544           Light
545           Light
546           Light
547           Heavy
548           Light
549     Ultra Light
550          Normal
551          Normal
552          Normal
553          Normal
554          Normal
555           Light
556          Normal
557          Normal
558          Normal
559     Ultra Light
560          Normal
561          Normal
562          Normal
563           Light
564          Normal
565           Light
566           Light
567          Normal
568           Light
569           Light
570           Light
571           Light
572          Normal
573          Normal
574          Normal
575           Light
576          Normal
577           Light
578           Heavy
579          Normal
580           Light
581     Ultra Light
582           Heavy
583          Normal
584          Normal
585          Normal
586           Light
587           Light
588           Heavy
589           Heavy
590           Light
591           Light
592           Light
593           Heavy
594           Light
595          Normal
596           Light
597          Normal
598           Light
599           Light
600           Light
601           Light
602           Light
603           Light
604     Ultra Light
605           Heavy
606           Light
607           Light
608           Light
609          Normal
610           Light
611          Normal
612     Ultra Light
613           Light
614     Ultra Light
615           Heavy
616           Light
617          Normal
618           Light
619          Normal
620          Normal
621           Light
622           Light
623          Normal
624          Normal
625          Normal
626          Normal
627          Normal
628          Normal
629          Normal
630          Normal
631           Light
632           Light
633           Light
634           Light
635           Heavy
636           Light
637          Normal
638           Light
639          Normal
640           Heavy
641          Normal
642          Normal
643           Light
644           Light
645          Normal
646          Normal
647          Normal
648          Normal
649          Normal
650          Normal
651          Normal
652          Normal
653          Normal
654          Normal
655          Normal
656          Normal
657           Light
658          Normal
659          Normal
660           Light
661          Normal
662          Normal
663           Light
664          Normal
665           Light
666          Normal
667          Normal
668          Normal
669          Normal
670          Normal
671           Light
672     Ultra Light
673     Ultra Light
674           Light
675           Light
676           Light
677           Light
678          Normal
679           Heavy
680           Light
681           Light
682          Normal
683           Heavy
684           Light
685          Normal
686           Heavy
687           Light
688           Light
689           Light
690          Normal
691           Light
692           Light
693           Light
694           Light
695           Light
696           Light
697           Light
698          Normal
699          Normal
700           Heavy
701          Normal
702          Normal
703          Normal
704          Normal
705     Ultra Light
706          Normal
707           Light
708           Heavy
709           Light
710           Light
711           Light
712          Normal
713           Heavy
714          Normal
715           Heavy
716           Light
717           Light
718           Light
719     Ultra Light
720           Light
721           Light
722     Ultra Light
723          Normal
724           Light
725           Light
726           Light
727          Normal
728           Light
729           Light
730          Normal
731          Normal
732          Normal
733           Light
734           Light
735           Heavy
736          Normal
737          Normal
738           Heavy
739           Light
740          Normal
741          Normal
742           Light
743          Normal
744           Light
745          Normal
746          Normal
747          Normal
748     Ultra Light
749           Light
750           Light
751          Normal
752          Normal
753          Normal
754          Normal
755           Light
756          Normal
757           Light
758           Light
759           Light
760           Heavy
761           Heavy
762           Heavy
763     Ultra Light
764          Normal
765          Normal
766           Light
767           Light
768           Light
769           Light
770          Normal
771           Light
772           Light
773          Normal
774           Light
775          Normal
776          Normal
777          Normal
778           Light
779           Light
780           Light
781           Light
782           Light
783           Light
784           Light
785          Normal
786           Light
787          Normal
788          Normal
789          Normal
790           Light
791           Light
792          Normal
793          Normal
794          Normal
795          Normal
796           Light
797           Light
798          Normal
799           Light
800          Normal
801           Light
802           Light
803           Heavy
804          Normal
805           Light
806           Light
807           Light
808           Light
809           Light
810           Light
811          Normal
812           Light
813           Light
814           Light
815          Normal
816          Normal
817           Light
818          Normal
819          Normal
820           Light
821           Light
822           Light
823           Light
824           Light
825           Light
826          Normal
827           Light
828           Light
829           Light
830           Light
831          Normal
832           Light
833          Normal
834          Normal
835          Normal
836           Light
837           Light
838           Light
839           Light
840           Light
841          Normal
842     Ultra Light
843           Light
844          Normal
845          Normal
846          Normal
847           Light
848           Light
849          Normal
850           Light
851     Ultra Light
852     Ultra Light
853          Normal
854           Light
855           Light
856           Light
857          Normal
858           Light
859           Light
860          Normal
861           Light
862           Light
863          Normal
864           Heavy
865          Normal
866           Heavy
867          Normal
868           Light
869           Light
870           Light
871           Light
872          Normal
873           Light
874           Light
875          Normal
876           Light
877           Light
878           Light
879          Normal
880          Normal
881          Normal
882           Light
883          Normal
884           Light
885          Normal
886           Light
887     Ultra Light
888          Normal
889           Heavy
890          Normal
891           Light
892          Normal
893           Light
894          Normal
895          Normal
896           Light
897           Light
898           Light
899           Heavy
900           Heavy
901           Light
902          Normal
903          Normal
904           Light
905          Normal
906           Light
907           Light
908           Light
909           Light
910           Light
911           Light
912           Light
913           Light
914     Ultra Light
915          Normal
916          Normal
917          Normal
918           Light
919           Light
920     Ultra Light
921     Ultra Light
922           Light
923          Normal
924           Light
925           Light
926     Ultra Light
927          Normal
928           Heavy
929           Light
930           Light
931           Heavy
932           Light
933           Light
934     Ultra Light
935           Light
936           Light
937          Normal
938           Light
939           Light
940          Normal
941           Heavy
942          Normal
943           Heavy
944           Heavy
945           Light
946           Light
947     Ultra Light
948           Light
949           Light
950           Light
951     Ultra Light
952           Light
953          Normal
954          Normal
955           Light
956           Light
957          Normal
958          Normal
959          Normal
960           Light
961           Light
962          Normal
963           Light
964           Light
965          Normal
966          Normal
967          Normal
968           Light
969           Light
970           Light
971          Normal
972          Normal
973           Light
974          Normal
975          Normal
976           Light
977          Normal
978           Light
979           Light
980          Normal
981          Normal
982           Light
983          Normal
984          Normal
985           Light
986           Light
987           Light
988           Heavy
989          Normal
990          Normal
991           Heavy
992           Light
993           Light
994          Normal
995           Light
996           Light
997           Heavy
998           Light
999     Ultra Light

- display size

In [419]:
df['Display Size'].unique()

array([14. , 16. , 15.6, 16.1, 14.1, 13.6, 13.3, 17.3, 11.6, 13. , 10.1,
       15.3, 13.4, 18. , 16.2, 15. , 13.5, 14.5,  nan, 12.5, 14.2, 11. ,
       12. , 12.3, 15.4, 10.5, 17. , 13.8, 12.4, 16.3, 14.9, 18.4, 12.2,
       11.3, 14.4, 16.6, 13.9, 15.8])

In [420]:
df['Display Size']=df['Display Size'].fillna(df['Display Size'].median())

- Display Resolution

In [421]:
df['Display Resolution']

0       1920 x 1080 Pixels
1       1920 x 1200 Pixels
2       1920 x 1080 Pixels
3       1920 x 1080 Pixels
4       1920 x 1080 Pixels
5       1920 x 1080 Pixels
6       1920 x 1080 Pixels
7       1920 x 1080 Pixels
8       2880 x 1800 Pixels
9       1920 x 1080 Pixels
10      1920 x 1080 Pixels
11      1920 x 1080 Pixels
12      1920 x 1080 Pixels
13      1920 x 1080 Pixels
14       1366 x 768 Pixels
15      1920 x 1080 Pixels
16      1920 x 1080 Pixels
17      1920 x 1080 Pixels
18      1920 x 1080 Pixels
19      1920 x 1080 Pixels
20      1920 x 1080 Pixels
21      1920 x 1080 Pixels
22      1920 x 1080 Pixels
23      1920 x 1080 Pixels
24      1920 x 1080 Pixels
25      1920 x 1080 Pixels
26       1366 x 768 Pixels
27      1920 x 1080 Pixels
28      1920 x 1080 Pixels
29      1920 x 1080 Pixels
30      1920 x 1080 Pixels
31      1920 x 1080 Pixels
32      1920 x 1080 Pixels
33      1920 x 1080 Pixels
34      1920 x 1080 Pixels
35      1920 x 1080 Pixels
36      1920 x 1080 Pixels
37       1366 x 768 Pixels
38      1920 x 1080 Pixels
39      1920 x 1080 Pixels
40      1920 x 1080 Pixels
41       1366 x 768 Pixels
42      1920 x 1200 Pixels
43      1920 x 1080 Pixels
44      1920 x 1080 Pixels
45      1920 x 1080 Pixels
46      2160 x 1440 Pixels
47       1366 x 768 Pixels
48      1920 x 1080 Pixels
49      1920 x 1080 Pixels
50      1920 x 1080 Pixels
51      1920 x 1080 Pixels
52      1920 x 1080 Pixels
53      1920 x 1080 Pixels
54      1920 x 1080 Pixels
55      1920 x 1080 Pixels
56      1920 x 1080 Pixels
57      2560 x 1664 Pixels
58       1366 x 768 Pixels
59      1920 x 1080 Pixels
60      1920 x 1080 Pixels
61      1920 x 1080 Pixels
62      1920 x 1080 Pixels
63       1366 x 768 Pixels
64       1366 x 768 Pixels
65      1920 x 1080 Pixels
66      1920 x 1080 Pixels
67      1920 x 1080 Pixels
68      1920 x 1080 Pixels
69      1920 x 1080 Pixels
70      1920 x 1080 Pixels
71      1920 x 1080 Pixels
72       1366 x 768 Pixels
73      1920 x 1080 Pixels
74      1920 x 1080 Pixels
75      1920 x 1080 Pixels
76      1920 x 1080 Pixels
77      1920 x 1080 Pixels
78       1366 x 768 Pixels
79      1920 x 1080 Pixels
80       1366 x 768 Pixels
81      1920 x 1080 Pixels
82      1920 x 1080 Pixels
83      1920 x 1080 Pixels
84      1920 x 1080 Pixels
85      1920 x 1080 Pixels
86      1920 x 1080 Pixels
87      1920 x 1080 Pixels
88      1920 x 1080 Pixels
89      1920 x 1080 Pixels
90      1920 x 1080 Pixels
91      1920 x 1080 Pixels
92      1920 x 1080 Pixels
93      1920 x 1080 Pixels
94      1920 x 1080 Pixels
95      1920 x 1080 Pixels
96      1920 x 1080 Pixels
97      1920 x 1080 Pixels
98      1920 x 1080 Pixels
99      1920 x 1080 Pixels
100     1920 x 1080 Pixels
101     1920 x 1080 Pixels
102     1920 x 1080 Pixels
103     1920 x 1080 Pixels
104     1920 x 1080 Pixels
105     1920 x 1080 Pixels
106     1920 x 1080 Pixels
107     1920 x 1080 Pixels
108      1366 x 768 Pixels
109     1920 x 1080 Pixels
110     1920 x 1080 Pixels
111     1920 x 1080 Pixels
112     1920 x 1080 Pixels
113     1920 x 1080 Pixels
114     1920 x 1080 Pixels
115     1920 x 1080 Pixels
116     1920 x 1080 Pixels
117     1920 x 1080 Pixels
118     1920 x 1080 Pixels
119     1920 x 1080 Pixels
120      1366 x 768 Pixels
121      1366 x 768 Pixels
122     2560 x 1600 Pixels
123     1920 x 1080 Pixels
124     1920 x 1080 Pixels
125     1920 x 1080 Pixels
126     1920 x 1080 Pixels
127     2560 x 1440 Pixels
128     2560 x 1440 Pixels
129     1920 x 1080 Pixels
130     1920 x 1080 Pixels
131      1366 x 768 Pixels
132     1920 x 1080 Pixels
133     1920 x 1080 Pixels
134      1366 x 768 Pixels
135     1920 x 1080 Pixels
136     1920 x 1080 Pixels
137      1366 x 768 Pixels
138      1366 x 768 Pixels
139      1366 x 768 Pixels
140     1920 x 1080 Pixels
141     1920 x 1080 Pixels
142     1920 x 1080 Pixels
143     1920 x 1200 Pixels
144     1920 x 1080 Pixels
145     1920 x 1080 Pixels
146     2560 x 1600 Pixels
147     1920 x 1080 Pixels
148     1920 x 1080 Pixels
149     1920 x 1080 Pixels
150     1920 x 1080 Pixels
151      1366 x 768 Pixels
152     1920 x 1200 Pixels
153     1920 x 1200 Pixels
154     1920 x 1080 Pixels
155     1920 x 1080 Pixels
156     1920 x 1080 Pixels
157     1920 x 1080 Pixels
158     1920 x 1080 Pixels
159     1920 x 1080 Pixels
160      1366 x 768 Pixels
161      1366 x 768 Pixels
162      1366 x 768 Pixels
163      1366 x 768 Pixels
164     1920 x 1080 Pixels
165     1920 x 1080 Pixels
166     1920 x 1080 Pixels
167     1920 x 1080 Pixels
168     1920 x 1080 Pixels
169     1920 x 1080 Pixels
170      1366 x 768 Pixels
171     1920 x 1080 Pixels
172     2560 x 1440 Pixels
173     2560 x 1440 Pixels
174     1920 x 1080 Pixels
175     1920 x 1080 Pixels
176     1920 x 1080 Pixels
177     1920 x 1080 Pixels
178      1366 x 768 Pixels
179      1366 x 768 Pixels
180     2560 x 1600 Pixels
181      1366 x 768 Pixels
182     1920 x 1080 Pixels
183     1920 x 1080 Pixels
184     1920 x 1080 Pixels
185     1920 x 1080 Pixels
186     2560 x 1600 Pixels
187     1920 x 1080 Pixels
188     1920 x 1080 Pixels
189     1920 x 1080 Pixels
190     1920 x 1080 Pixels
191     1920 x 1080 Pixels
192     1920 x 1080 Pixels
193      1366 x 768 Pixels
194     1920 x 1080 Pixels
195     1920 x 1080 Pixels
196     1920 x 1080 Pixels
197     2560 x 1600 Pixels
198     1920 x 1080 Pixels
199     1920 x 1080 Pixels
200      1366 x 768 Pixels
201     2880 x 1800 Pixels
202      1366 x 768 Pixels
203     2880 x 1800 Pixels
204      1366 x 768 Pixels
205      1366 x 768 Pixels
206     1920 x 1080 Pixels
207      1366 x 768 Pixels
208     1920 x 1080 Pixels
209      1366 x 768 Pixels
210      1366 x 768 Pixels
211      1366 x 768 Pixels
212      1366 x 768 Pixels
213      1366 x 768 Pixels
214     1920 x 1200 Pixels
215      1280 x 800 Pixels
216      1366 x 768 Pixels
217     1920 x 1080 Pixels
218      1366 x 768 Pixels
219      1366 x 768 Pixels
220      1366 x 768 Pixels
221      1366 x 768 Pixels
222     2560 x 1600 Pixels
223     1920 x 1200 Pixels
224     1920 x 1080 Pixels
225     1920 x 1080 Pixels
226      1366 x 768 Pixels
227      1600 x 900 Pixels
228     1920 x 1080 Pixels
229      1366 x 768 Pixels
230     1920 x 1080 Pixels
231      1366 x 768 Pixels
232     1920 x 1080 Pixels
233     1920 x 1080 Pixels
234      1366 x 768 Pixels
235     1920 x 1080 Pixels
236      1366 x 768 Pixels
237      1366 x 768 Pixels
238      1366 x 768 Pixels
239      1366 x 768 Pixels
240      1366 x 768 Pixels
241      1366 x 768 Pixels
242     2880 x 1800 Pixels
243     1920 x 1080 Pixels
244     1920 x 1080 Pixels
245     1920 x 1080 Pixels
246      1366 x 768 Pixels
247     1920 x 1080 Pixels
248     1920 x 1080 Pixels
249      1366 x 768 Pixels
250      1366 x 768 Pixels
251     1920 x 1080 Pixels
252      1366 x 768 Pixels
253     1920 x 1080 Pixels
254      1366 x 768 Pixels
255     1920 x 1080 Pixels
256     1920 x 1080 Pixels
257      1366 x 768 Pixels
258      1366 x 768 Pixels
259     1920 x 1080 Pixels
260     1920 x 1080 Pixels
261      1366 x 768 Pixels
262     1920 x 1080 Pixels
263      1366 x 768 Pixels
264     1920 x 1080 Pixels
265     2880 x 1620 Pixels
266     1920 x 1080 Pixels
267      1366 x 768 Pixels
268     1920 x 1080 Pixels
269     2560 x 1440 Pixels
270     1920 x 1080 Pixels
271     1920 x 1200 Pixels
272      1366 x 768 Pixels
273      1366 x 768 Pixels
274     1920 x 1080 Pixels
275     1920 x 1080 Pixels
276      1366 x 768 Pixels
277     1920 x 1080 Pixels
278     1920 x 1080 Pixels
279     1920 x 1080 Pixels
280     1920 x 1080 Pixels
281      1366 x 768 Pixels
282     1920 x 1080 Pixels
283      1366 x 768 Pixels
284     1920 x 1080 Pixels
285     1920 x 1080 Pixels
286     1920 x 1200 Pixels
287     1920 x 1200 Pixels
288     1920 x 1080 Pixels
289     2560 x 1440 Pixels
290     1920 x 1080 Pixels
291     1920 x 1080 Pixels
292     3840 x 2160 Pixels
293      1366 x 768 Pixels
294     1920 x 1080 Pixels
295      1366 x 768 Pixels
296     1920 x 1080 Pixels
297      1366 x 768 Pixels
298      1366 x 768 Pixels
299     2560 x 1600 Pixels
300     2560 x 1440 Pixels
301      1366 x 768 Pixels
302     1920 x 1200 Pixels
303     1920 x 1080 Pixels
304      1366 x 768 Pixels
305      1366 x 768 Pixels
306     1920 x 1200 Pixels
307     1920 x 1200 Pixels
308     1920 x 1080 Pixels
309      1366 x 768 Pixels
310     2560 x 1440 Pixels
311      1366 x 768 Pixels
312     1920 x 1080 Pixels
313     1920 x 1080 Pixels
314     1920 x 1080 Pixels
315     2560 x 1440 Pixels
316     1920 x 1080 Pixels
317     1920 x 1080 Pixels
318     1920 x 1080 Pixels
319     2560 x 1600 Pixels
320     1920 x 1080 Pixels
321     1920 x 1080 Pixels
322     1920 x 1080 Pixels
323      1366 x 768 Pixels
324      1366 x 768 Pixels
325      1366 x 768 Pixels
326     1920 x 1080 Pixels
327     1920 x 1080 Pixels
328     1920 x 1080 Pixels
329     1920 x 1080 Pixels
330     1920 x 1080 Pixels
331     3840 x 2160 Pixels
332     1920 x 1080 Pixels
333     1920 x 1080 Pixels
334     1920 x 1200 Pixels
335     1920 x 1080 Pixels
336     2560 x 1600 Pixels
337      1366 x 768 Pixels
338     2560 x 1440 Pixels
339     1920 x 1080 Pixels
340     1920 x 1200 Pixels
341      1366 x 768 Pixels
342     1920 x 1080 Pixels
343     1920 x 1080 Pixels
344     1920 x 1080 Pixels
345     1920 x 1080 Pixels
346     1920 x 1080 Pixels
347     1920 x 1080 Pixels
348      1366 x 768 Pixels
349     1920 x 1080 Pixels
350     2560 x 1600 Pixels
351     1920 x 1200 Pixels
352     1920 x 1080 Pixels
353     1920 x 1080 Pixels
354     2880 x 1800 Pixels
355      1366 x 768 Pixels
356     1920 x 1200 Pixels
357     1920 x 1200 Pixels
358     1920 x 1200 Pixels
359     1920 x 1080 Pixels
360     1920 x 1080 Pixels
361     1920 x 1080 Pixels
362     2560 x 1600 Pixels
363     1920 x 1200 Pixels
364     1920 x 1080 Pixels
365     1920 x 1080 Pixels
366     2560 x 1600 Pixels
367     2880 x 1800 Pixels
368     1920 x 1080 Pixels
369     1920 x 1080 Pixels
370     1920 x 1080 Pixels
371     1920 x 1080 Pixels
372      1366 x 768 Pixels
373      1366 x 768 Pixels
374     2560 x 1440 Pixels
375      1366 x 768 Pixels
376     1920 x 1080 Pixels
377     1920 x 1080 Pixels
378     1920 x 1080 Pixels
379     3840 x 2400 Pixels
380     1920 x 1080 Pixels
381     2880 x 1800 Pixels
382     1920 x 1200 Pixels
383     1920 x 1080 Pixels
384     2880 x 1800 Pixels
385     1920 x 1080 Pixels
386     1920 x 1200 Pixels
387     2880 x 1800 Pixels
388     1920 x 1200 Pixels
389     1920 x 1200 Pixels
390     1920 x 1200 Pixels
391     2880 x 1800 Pixels
392     2560 x 1600 Pixels
393     1920 x 1080 Pixels
394     1920 x 1200 Pixels
395     1920 x 1200 Pixels
396     2880 x 1800 Pixels
397     2880 x 1800 Pixels
398     1920 x 1080 Pixels
399     2880 x 1800 Pixels
400     1920 x 1080 Pixels
401     1920 x 1080 Pixels
402      1366 x 768 Pixels
403     1920 x 1080 Pixels
404     1920 x 1080 Pixels
405     1920 x 1080 Pixels
406     1920 x 1080 Pixels
407     1920 x 1080 Pixels
408     1920 x 1080 Pixels
409     1920 x 1080 Pixels
410     1920 x 1080 Pixels
411     1920 x 1080 Pixels
412      1366 x 768 Pixels
413     1920 x 1080 Pixels
414     1920 x 1080 Pixels
415      1366 x 768 Pixels
416     1920 x 1080 Pixels
417      1366 x 768 Pixels
418     1920 x 1080 Pixels
419     1920 x 1080 Pixels
420     1920 x 1080 Pixels
421     1920 x 1080 Pixels
422     1920 x 1080 Pixels
423     1920 x 1080 Pixels
424     2880 x 1800 Pixels
425     1920 x 1080 Pixels
426     1920 x 1080 Pixels
427     1920 x 1080 Pixels
428     1920 x 1080 Pixels
429     1920 x 1080 Pixels
430      1366 x 768 Pixels
431     1920 x 1080 Pixels
432     1920 x 1080 Pixels
433     1920 x 1080 Pixels
434     1920 x 1080 Pixels
435     1920 x 1080 Pixels
436     1920 x 1080 Pixels
437     1920 x 1080 Pixels
438     1920 x 1080 Pixels
439     1920 x 1080 Pixels
440     1920 x 1080 Pixels
441      1366 x 768 Pixels
442     1920 x 1080 Pixels
443      1366 x 768 Pixels
444     1920 x 1080 Pixels
445     1920 x 1080 Pixels
446     1920 x 1080 Pixels
447     1920 x 1080 Pixels
448     1920 x 1080 Pixels
449     1920 x 1080 Pixels
450      1366 x 768 Pixels
451      1366 x 768 Pixels
452     1920 x 1080 Pixels
453      1366 x 768 Pixels
454     1920 x 1080 Pixels
455      1366 x 768 Pixels
456      1366 x 768 Pixels
457     1920 x 1080 Pixels
458     1920 x 1080 Pixels
459     1920 x 1080 Pixels
460     1920 x 1080 Pixels
461     1920 x 1080 Pixels
462      1366 x 768 Pixels
463     1920 x 1080 Pixels
464     2560 x 1600 Pixels
465      1366 x 768 Pixels
466     1920 x 1080 Pixels
467     1920 x 1080 Pixels
468     2560 x 1600 Pixels
469     1920 x 1080 Pixels
470     1920 x 1080 Pixels
471     1920 x 1080 Pixels
472     2240 x 1400 Pixels
473     1920 x 1080 Pixels
474     1920 x 1080 Pixels
475     1920 x 1080 Pixels
476     1920 x 1080 Pixels
477     1920 x 1080 Pixels
478      1366 x 768 Pixels
479      1366 x 768 Pixels
480      1366 x 768 Pixels
481     1920 x 1080 Pixels
482      1366 x 768 Pixels
483     1920 x 1080 Pixels
484     1920 x 1080 Pixels
485     1920 x 1080 Pixels
486     1920 x 1080 Pixels
487     1920 x 1080 Pixels
488     1920 x 1080 Pixels
489     1920 x 1080 Pixels
490     2560 x 1600 Pixels
491     1920 x 1080 Pixels
492     1920 x 1080 Pixels
493     1920 x 1080 Pixels
494     1920 x 1080 Pixels
495     1920 x 1080 Pixels
496     1920 x 1080 Pixels
497      1366 x 768 Pixels
498     3456 x 2234 Pixels
499     1920 x 1080 Pixels
500      1366 x 768 Pixels
501     1920 x 1080 Pixels
502     1920 x 1080 Pixels
503     1920 x 1080 Pixels
504     1920 x 1080 Pixels
505     1920 x 1080 Pixels
506     1920 x 1080 Pixels
507     1920 x 1080 Pixels
508     1920 x 1080 Pixels
509     1920 x 1080 Pixels
510     2560 x 1600 Pixels
511     1920 x 1080 Pixels
512     1920 x 1200 Pixels
513     1920 x 1080 Pixels
514     1920 x 1080 Pixels
515     1920 x 1080 Pixels
516      1366 x 768 Pixels
517     1920 x 1080 Pixels
518     2560 x 1600 Pixels
519     1920 x 1080 Pixels
520      1366 x 768 Pixels
521     1920 x 1080 Pixels
522     1920 x 1080 Pixels
523      1366 x 768 Pixels
524      1366 x 768 Pixels
525     1920 x 1080 Pixels
526     1920 x 1080 Pixels
527     1920 x 1080 Pixels
528     1920 x 1080 Pixels
529     1920 x 1080 Pixels
530      1366 x 768 Pixels
531      1366 x 768 Pixels
532      1366 x 768 Pixels
533      1366 x 768 Pixels
534     1920 x 1080 Pixels
535      1366 x 768 Pixels
536     1920 x 1080 Pixels
537     1920 x 1080 Pixels
538     1920 x 1080 Pixels
539     1920 x 1080 Pixels
540     1920 x 1080 Pixels
541     1920 x 1080 Pixels
542     1920 x 1080 Pixels
543     1920 x 1080 Pixels
544     2880 x 1800 Pixels
545      1366 x 768 Pixels
546     2880 x 1800 Pixels
547     1920 x 1080 Pixels
548     1920 x 1080 Pixels
549      1366 x 768 Pixels
550     1920 x 1080 Pixels
551     1920 x 1080 Pixels
552     1920 x 1080 Pixels
553     1920 x 1080 Pixels
554      1366 x 768 Pixels
555     1920 x 1080 Pixels
556      1366 x 768 Pixels
557     1920 x 1080 Pixels
558     1920 x 1080 Pixels
559      1366 x 768 Pixels
560     1920 x 1080 Pixels
561     1920 x 1080 Pixels
562     1920 x 1080 Pixels
563     1920 x 1080 Pixels
564     1920 x 1080 Pixels
565     1920 x 1080 Pixels
566     1920 x 1080 Pixels
567     1920 x 1080 Pixels
568     1920 x 1080 Pixels
569     1920 x 1080 Pixels
570     1920 x 1080 Pixels
571     1920 x 1080 Pixels
572     1920 x 1080 Pixels
573     1920 x 1080 Pixels
574     1920 x 1080 Pixels
575     1920 x 1080 Pixels
576     1920 x 1080 Pixels
577     1920 x 1080 Pixels
578     1920 x 1080 Pixels
579     1920 x 1080 Pixels
580     1920 x 1080 Pixels
581     1920 x 1080 Pixels
582     1920 x 1080 Pixels
583     1920 x 1080 Pixels
584     1920 x 1080 Pixels
585      1366 x 768 Pixels
586     1920 x 1080 Pixels
587      1366 x 768 Pixels
588     1920 x 1200 Pixels
589     1920 x 1200 Pixels
590     1920 x 1080 Pixels
591     1920 x 1080 Pixels
592     1920 x 1080 Pixels
593     2560 x 1440 Pixels
594     1920 x 1080 Pixels
595      1366 x 768 Pixels
596      1366 x 768 Pixels
597     1920 x 1080 Pixels
598     1920 x 1080 Pixels
599     1920 x 1080 Pixels
600     2880 x 1800 Pixels
601     2240 x 1400 Pixels
602     1920 x 1080 Pixels
603     1920 x 1080 Pixels
604     2880 x 1800 Pixels
605     2560 x 1600 Pixels
606     1920 x 1080 Pixels
607     1920 x 1080 Pixels
608     1920 x 1080 Pixels
609     1920 x 1200 Pixels
610     1920 x 1080 Pixels
611     1920 x 1080 Pixels
612     1920 x 1200 Pixels
613     1920 x 1080 Pixels
614     1920 x 1200 Pixels
615     1920 x 1200 Pixels
616     2880 x 1800 Pixels
617     1920 x 1200 Pixels
618     1920 x 1080 Pixels
619     1920 x 1200 Pixels
620     1920 x 1080 Pixels
621     1920 x 1080 Pixels
622     1920 x 1080 Pixels
623     2880 x 1920 Pixels
624     1920 x 1080 Pixels
625     1920 x 1200 Pixels
626     1920 x 1080 Pixels
627     1920 x 1080 Pixels
628     1920 x 1080 Pixels
629     1920 x 1080 Pixels
630     2560 x 1600 Pixels
631     1920 x 1200 Pixels
632     2880 x 1800 Pixels
633     1920 x 1200 Pixels
634     1920 x 1080 Pixels
635     1920 x 1200 Pixels
636     2880 x 1800 Pixels
637     1920 x 1080 Pixels
638     1920 x 1080 Pixels
639     1920 x 1080 Pixels
640     3840 x 2400 Pixels
641     1920 x 1080 Pixels
642     1920 x 1200 Pixels
643     2880 x 1864 Pixels
644     1920 x 1200 Pixels
645     2880 x 1920 Pixels
646     1920 x 1200 Pixels
647     1920 x 1200 Pixels
648     1920 x 1200 Pixels
649     1920 x 1200 Pixels
650     1920 x 1200 Pixels
651     1920 x 1200 Pixels
652      1366 x 768 Pixels
653     2560 x 1600 Pixels
654     2240 x 1400 Pixels
655     1920 x 1080 Pixels
656     1920 x 1200 Pixels
657     2560 x 1600 Pixels
658     1920 x 1200 Pixels
659     1920 x 1080 Pixels
660     1920 x 1200 Pixels
661     1920 x 1080 Pixels
662     1920 x 1200 Pixels
663     1920 x 1080 Pixels
664     1920 x 1200 Pixels
665     1920 x 1080 Pixels
666     1920 x 1080 Pixels
667     1920 x 1080 Pixels
668     1920 x 1200 Pixels
669     1920 x 1200 Pixels
670     1920 x 1080 Pixels
671     2880 x 1800 Pixels
672      1366 x 768 Pixels
673     1920 x 1200 Pixels
674     1920 x 1200 Pixels
675     1920 x 1200 Pixels
676     1920 x 1080 Pixels
677     1920 x 1080 Pixels
678     1920 x 1080 Pixels
679     1920 x 1080 Pixels
680     1920 x 1200 Pixels
681     1920 x 1080 Pixels
682     1920 x 1200 Pixels
683     2560 x 1600 Pixels
684     1920 x 1080 Pixels
685     2560 x 1600 Pixels
686     2560 x 1600 Pixels
687     1920 x 1080 Pixels
688     1920 x 1200 Pixels
689     1920 x 1200 Pixels
690     1920 x 1080 Pixels
691     1920 x 1200 Pixels
692     1920 x 1200 Pixels
693     1920 x 1200 Pixels
694     1920 x 1200 Pixels
695     1920 x 1200 Pixels
696     3840 x 2400 Pixels
697     1920 x 1200 Pixels
698     1920 x 1200 Pixels
699     1920 x 1200 Pixels
700     1920 x 1080 Pixels
701     1920 x 1200 Pixels
702     1920 x 1200 Pixels
703     1920 x 1200 Pixels
704     1920 x 1200 Pixels
705     1920 x 1200 Pixels
706     1920 x 1200 Pixels
707     2880 x 1800 Pixels
708     1920 x 1080 Pixels
709     1920 x 1200 Pixels
710     1920 x 1200 Pixels
711     1920 x 1080 Pixels
712     1920 x 1200 Pixels
713     2560 x 1600 Pixels
714     3200 x 2000 Pixels
715     1920 x 1080 Pixels
716     1920 x 1200 Pixels
717     1920 x 1200 Pixels
718     1920 x 1200 Pixels
719     1920 x 1280 Pixels
720     1920 x 1080 Pixels
721     1920 x 1200 Pixels
722     2880 x 1800 Pixels
723     1920 x 1080 Pixels
724     1920 x 1080 Pixels
725     1920 x 1080 Pixels
726     1920 x 1200 Pixels
727     1920 x 1200 Pixels
728     1920 x 1200 Pixels
729     1920 x 1080 Pixels
730     1920 x 1200 Pixels
731     1920 x 1200 Pixels
732     1920 x 1200 Pixels
733     1920 x 1200 Pixels
734     2880 x 1800 Pixels
735     1920 x 1200 Pixels
736     1920 x 1080 Pixels
737     1920 x 1200 Pixels
738     1920 x 1200 Pixels
739     1920 x 1200 Pixels

In [422]:
df['Display Resolution'].mode()[0]

'1920 x 1080 Pixels'

In [423]:
df['Display Resolution'] = df['Display Resolution'].fillna(
    df['Display Resolution'].mode()[0]
)

In [424]:
df[['Resolution_X', 'Resolution_Y']] = (
    df['Display Resolution']
    .str.extract(r'(\d+)\s*x\s*(\d+)')
    .astype(int)
)

In [425]:
df=df.drop('Display Resolution',axis=1)

- Pixel Density

In [426]:
df['Pixel Density']

0       157 ppi
1       142 ppi
2       141 ppi
3       141 ppi
4       141 ppi
5       141 ppi
6       141 ppi
7       157 ppi
8       243 ppi
9       157 ppi
10      141 ppi
11      157 ppi
12      141 ppi
13      141 ppi
14      100 ppi
15      157 ppi
16      141 ppi
17      141 ppi
18      141 ppi
19      141 ppi
20      157 ppi
21      141 ppi
22      141 ppi
23      157 ppi
24      141 ppi
25      157 ppi
26      100 ppi
27      137 ppi
28      141 ppi
29      141 ppi
30      141 ppi
31      141 ppi
32      141 ppi
33      141 ppi
34      157 ppi
35      157 ppi
36      141 ppi
37      100 ppi
38      141 ppi
39      156 ppi
40      157 ppi
41      100 ppi
42      142 ppi
43      141 ppi
44      156 ppi
45      141 ppi
46      185 ppi
47      100 ppi
48      141 ppi
49      141 ppi
50      141 ppi
51      141 ppi
52      141 ppi
53      157 ppi
54      141 ppi
55      141 ppi
56      141 ppi
57      225 ppi
58      100 ppi
59      141 ppi
60      157 ppi
61      141 ppi
62      141 ppi
63      100 ppi
64      112 ppi
65      141 ppi
66      157 ppi
67      141 ppi
68      141 ppi
69      166 ppi
70      141 ppi
71      141 ppi
72      100 ppi
73      157 ppi
74      141 ppi
75      141 ppi
76      127 ppi
77      141 ppi
78      100 ppi
79      141 ppi
80      100 ppi
81      141 ppi
82      157 ppi
83      141 ppi
84      141 ppi
85      190 ppi
86      141 ppi
87      157 ppi
88      157 ppi
89      141 ppi
90      141 ppi
91      166 ppi
92      141 ppi
93      141 ppi
94      141 ppi
95      141 ppi
96      141 ppi
97      141 ppi
98      157 ppi
99      141 ppi
100     141 ppi
101     141 ppi
102     157 ppi
103     157 ppi
104     141 ppi
105     141 ppi
106     141 ppi
107     141 ppi
108     135 ppi
109     157 ppi
110     157 ppi
111     141 ppi
112     141 ppi
113     141 ppi
114     141 ppi
115     141 ppi
116     141 ppi
117     141 ppi
118     141 ppi
119     157 ppi
120     112 ppi
121     135 ppi
122     232 ppi
123     141 ppi
124     157 ppi
125     157 ppi
126     127 ppi
127     188 ppi
128     188 ppi
129     141 ppi
130     141 ppi
131     112 ppi
132     141 ppi
133     141 ppi
134     100 ppi
135     141 ppi
136     157 ppi
137     100 ppi
138     100 ppi
139     112 ppi
140     141 ppi
141     141 ppi
142     157 ppi
143     162 ppi
144     141 ppi
145     141 ppi
146     227 ppi
147     166 ppi
148     141 ppi
149     157 ppi
150     157 ppi
151     100 ppi
152     162 ppi
153     162 ppi
154     166 ppi
155     141 ppi
156     141 ppi
157     141 ppi
158     141 ppi
159     157 ppi
160     100 ppi
161     100 ppi
162     100 ppi
163     112 ppi
164     141 ppi
165     141 ppi
166     141 ppi
167     141 ppi
168     157 ppi
169     141 ppi
170     100 ppi
171     157 ppi
172     210 ppi
173     210 ppi
174     141 ppi
175     141 ppi
176     141 ppi
177     157 ppi
178     100 ppi
179     100 ppi
180     227 ppi
181     100 ppi
182     157 ppi
183     157 ppi
184     157 ppi
185     127 ppi
186     227 ppi
187     141 ppi
188     157 ppi
189     141 ppi
190     157 ppi
191     157 ppi
192     141 ppi
193     112 ppi
194     137 ppi
195     157 ppi
196     141 ppi
197     227 ppi
198     141 ppi
199     141 ppi
200     112 ppi
201     243 ppi
202     100 ppi
203     243 ppi
204     100 ppi
205     100 ppi
206     141 ppi
207     100 ppi
208     157 ppi
209     135 ppi
210     100 ppi
211     100 ppi
212     100 ppi
213     100 ppi
214     142 ppi
215     149 ppi
216     100 ppi
217     141 ppi
218     100 ppi
219     100 ppi
220     100 ppi
221     100 ppi
222     189 ppi
223     142 ppi
224     166 ppi
225     141 ppi
226     100 ppi
227     106 ppi
228     141 ppi
229     100 ppi
230     141 ppi
231     100 ppi
232     157 ppi
233     141 ppi
234     100 ppi
235     141 ppi
236     135 ppi
237     100 ppi
238     100 ppi
239     112 ppi
240     100 ppi
241     118 ppi
242     243 ppi
243     141 ppi
244     141 ppi
245     141 ppi
246     100 ppi
247     127 ppi
248     141 ppi
249     100 ppi
250     100 ppi
251     141 ppi
252     112 ppi
253     141 ppi
254     100 ppi
255     157 ppi
256     141 ppi
257     100 ppi
258     100 ppi
259     141 ppi
260     141 ppi
261     112 ppi
262     141 ppi
263     100 ppi
264     157 ppi
265     212 ppi
266     141 ppi
267     100 ppi
268     141 ppi
269     210 ppi
270     138 ppi
271     162 ppi
272     135 ppi
273     112 ppi
274     157 ppi
275     127 ppi
276     100 ppi
277     157 ppi
278     157 ppi
279     157 ppi
280     141 ppi
281     100 ppi
282     157 ppi
283     155 ppi
284     141 ppi
285     141 ppi
286     162 ppi
287     142 ppi
288     141 ppi
289     188 ppi
290     141 ppi
291     141 ppi
292     255 ppi
293     112 ppi
294     157 ppi
295     118 ppi
296     157 ppi
297     102 ppi
298     100 ppi
299     189 ppi
300     210 ppi
301     135 ppi
302     142 ppi
303     157 ppi
304     100 ppi
305     135 ppi
306     142 ppi
307     169 ppi
308     157 ppi
309     100 ppi
310     188 ppi
311     100 ppi
312     141 ppi
313     141 ppi
314     141 ppi
315     188 ppi
316     141 ppi
317     141 ppi
318     141 ppi
319     189 ppi
320     157 ppi
321     141 ppi
322     141 ppi
323     100 ppi
324     112 ppi
325     111 ppi
326     141 ppi
327     141 ppi
328     141 ppi
329     141 ppi
330     157 ppi
331     255 ppi
332     157 ppi
333     141 ppi
334     142 ppi
335     141 ppi
336     189 ppi
337     112 ppi
338     170 ppi
339     141 ppi
340     142 ppi
341     100 ppi
342     157 ppi
343     157 ppi
344     141 ppi
345     157 ppi
346     141 ppi
347     157 ppi
348     112 ppi
349     141 ppi
350     168 ppi
351     169 ppi
352     127 ppi
353     166 ppi
354     212 ppi
355     112 ppi
356     162 ppi
357     162 ppi
358     142 ppi
359     157 ppi
360     127 ppi
361     127 ppi
362     189 ppi
363     169 ppi
364     141 ppi
365     157 ppi
366     216 ppi
367     243 ppi
368     127 ppi
369     141 ppi
370     157 ppi
371     141 ppi
372     100 ppi
373     100 ppi
374     188 ppi
375     100 ppi
376     141 ppi
377     141 ppi
378     157 ppi
379     338 ppi
380     141 ppi
381     243 ppi
382     170 ppi
383     141 ppi
384     243 ppi
385     141 ppi
386     162 ppi
387     243 ppi
388     142 ppi
389     162 ppi
390     162 ppi
391     212 ppi
392     227 ppi
393     141 ppi
394     142 ppi
395     142 ppi
396     243 ppi
397     243 ppi
398     141 ppi
399     243 ppi
400     157 ppi
401     141 ppi
402     100 ppi
403     157 ppi
404     141 ppi
405     141 ppi
406     141 ppi
407     141 ppi
408     141 ppi
409     157 ppi
410     141 ppi
411     141 ppi
412     100 ppi
413     141 ppi
414     157 ppi
415     112 ppi
416     157 ppi
417     100 ppi
418     157 ppi
419     141 ppi
420     141 ppi
421     157 ppi
422     141 ppi
423     141 ppi
424     243 ppi
425     157 ppi
426     141 ppi
427     157 ppi
428     141 ppi
429     157 ppi
430     112 ppi
431     141 ppi
432     141 ppi
433     141 ppi
434     141 ppi
435     141 ppi
436     141 ppi
437     141 ppi
438     141 ppi
439     157 ppi
440     141 ppi
441     112 ppi
442     141 ppi
443     112 ppi
444     141 ppi
445     141 ppi
446     141 ppi
447     141 ppi
448     141 ppi
449     141 ppi
450     112 ppi
451     100 ppi
452     141 ppi
453     135 ppi
454     157 ppi
455     112 ppi
456     100 ppi
457     157 ppi
458     141 ppi
459     141 ppi
460     157 ppi
461     141 ppi
462     100 ppi
463     141 ppi
464     227 ppi
465     100 ppi
466     141 ppi
467     157 ppi
468     227 ppi
469     141 ppi
470     157 ppi
471     157 ppi
472     189 ppi
473     141 ppi
474     141 ppi
475     141 ppi
476     141 ppi
477     141 ppi
478     100 ppi
479     100 ppi
480     112 ppi
481     141 ppi
482     100 ppi
483     141 ppi
484     141 ppi
485     141 ppi
486     141 ppi
487     141 ppi
488     141 ppi
489     141 ppi
490     227 ppi
491     157 ppi
492     141 ppi
493     127 ppi
494     141 ppi
495     141 ppi
496     141 ppi
497     100 ppi
498     254 ppi
499     141 ppi
500     100 ppi
501     141 ppi
502     157 ppi
503     141 ppi
504     141 ppi
505     157 ppi
506     141 ppi
507     141 ppi
508     141 ppi
509     141 ppi
510     227 ppi
511     147 ppi
512     142 ppi
513     141 ppi
514     141 ppi
515     141 ppi
516     135 ppi
517     141 ppi
518     227 ppi
519     141 ppi
520     135 ppi
521     141 ppi
522     141 ppi
523     100 ppi
524     135 ppi
525     157 ppi
526     141 ppi
527     141 ppi
528     157 ppi
529     141 ppi
530     135 ppi
531     112 ppi
532     112 ppi
533     135 ppi
534     141 ppi
535     100 ppi
536     141 ppi
537     157 ppi
538     141 ppi
539     141 ppi
540     141 ppi
541     141 ppi
542     141 ppi
543     141 ppi
544     243 ppi
545     112 ppi
546     243 ppi
547     141 ppi
548     157 ppi
549     112 ppi
550     141 ppi
551     141 ppi
552     141 ppi
553     141 ppi
554     100 ppi
555     141 ppi
556     100 ppi
557     141 ppi
558     141 ppi
559     112 ppi
560     157 ppi
561     141 ppi
562     141 ppi
563     141 ppi
564     141 ppi
565     157 ppi
566     141 ppi
567     141 ppi
568     141 ppi
569     141 ppi
570     157 ppi
571     141 ppi
572     141 ppi
573     141 ppi
574     141 ppi
575     141 ppi
576     141 ppi
577     157 ppi
578     137 ppi
579     141 ppi
580     141 ppi
581     157 ppi
582     137 ppi
583     141 ppi
584     141 ppi
585     100 ppi
586     157 ppi
587     112 ppi
588     142 ppi
589     142 ppi
590     141 ppi
591     141 ppi
592     157 ppi
593     188 ppi
594     157 ppi
595     112 ppi
596     112 ppi
597     141 ppi
598     141 ppi
599     141 ppi
600     243 ppi
601     189 ppi
602     157 ppi
603     141 ppi
604     243 ppi
605     189 ppi
606     141 ppi
607     141 ppi
608     141 ppi
609     162 ppi
610     157 ppi
611     141 ppi
612     162 ppi
613     157 ppi
614     162 ppi
615     142 ppi
616     243 ppi
617     162 ppi
618     157 ppi
619     162 ppi
620     141 ppi
621     141 ppi
622     141 ppi
623     256 ppi
624     141 ppi
625     162 ppi
626     141 ppi
627     141 ppi
628     141 ppi
629     141 ppi
630     189 ppi
631     162 ppi
632     243 ppi
633     162 ppi
634     141 ppi
635     142 ppi
636     243 ppi
637     141 ppi
638     141 ppi
639     141 ppi
640     252 ppi
641     141 ppi
642     162 ppi
643     224 ppi
644     162 ppi
645     256 ppi
646     162 ppi
647     142 ppi
648     162 ppi
649     170 ppi
650     142 ppi
651     162 ppi
652     100 ppi
653     189 ppi
654     189 ppi
655     157 ppi
656     170 ppi
657     216 ppi
658     170 ppi
659     141 ppi
660     170 ppi
661     141 ppi
662     162 ppi
663     157 ppi
664     162 ppi
665     141 ppi
666     141 ppi
667     141 ppi
668     162 ppi
669     170 ppi
670     157 ppi
671     243 ppi
672     135 ppi
673     162 ppi
674     162 ppi
675     162 ppi
676     157 ppi
677     141 ppi
678     141 ppi
679     141 ppi
680     162 ppi
681     141 ppi
682     162 ppi
683     189 ppi
684     141 ppi
685     189 ppi
686     189 ppi
687     141 ppi
688     142 ppi
689     142 ppi
690     141 ppi
691     142 ppi
692     142 ppi
693     142 ppi
694     142 ppi
695     142 ppi
696     283 ppi
697     142 ppi
698     162 ppi
699     162 ppi
700     141 ppi
701     162 ppi
702     162 ppi
703     142 ppi
704     162 ppi
705     162 ppi
706     162 ppi
707     243 ppi
708     141 ppi
709     162 ppi
710     162 ppi
711     141 ppi
712     162 ppi
713     189 ppi
714     236 ppi
715     141 ppi
716     170 ppi
717     162 ppi
718     170 ppi
719     171 ppi
720     141 ppi
721     162 ppi
722     255 ppi
723     141 ppi
724     141 ppi
725     141 ppi
726     162 ppi
727     162 ppi
728     162 ppi
729     141 ppi
730     142 ppi
731     142 ppi
732     162 ppi
733     162 ppi
734     243 ppi
735     162 ppi
736     157 ppi
737     162 ppi
738     162 ppi
739     142 ppi
740     142 ppi
741     141 ppi
742     162 ppi
743     236 ppi
744         NaN
745     157 ppi
746     222 ppi
747     141 ppi
748     225 ppi
749     157 ppi
750     141 ppi
751     141 ppi
752     141 ppi
753     135 ppi
754     142 ppi
755     156 ppi
756     141 ppi
757     141 ppi
758     224 ppi
759     141 ppi
760         NaN
761         NaN
762     182 ppi
763     243 ppi
764     157 ppi
765     189 ppi
766     141 ppi
767     141 ppi
768     162 ppi
769     112 ppi
770     141 ppi
771     157 ppi
772     141 ppi
773     142 ppi
774     141 ppi
775     162 ppi
776     157 ppi
777     162 ppi
778     141 ppi
779     141 ppi
780     162 ppi
781     141 ppi
782     141 ppi
783     141 ppi
784     157 ppi
785     141 ppi
786     141 ppi
787     141 ppi
788     162 ppi
789     141 ppi
790     141 ppi
791     166 ppi
792     141 ppi
793     151 ppi
794     162 ppi
795     156 ppi
796     157 ppi
797         NaN
798     142 ppi
799     100 ppi
800     100 ppi
801     141 ppi
802     100 ppi
803     141 ppi
804     141 ppi
805     141 ppi
806     141 ppi
807     157 ppi
808     141 ppi
809     100 ppi
810     112 ppi
811     141 ppi
812     157 ppi
813     157 ppi
814     141 ppi
815     141 ppi
816     100 ppi
817     157 ppi
818     100 ppi
819     141 ppi
820     141 ppi
821     141 ppi
822     141 ppi
823     141 ppi
824     141 ppi
825     141 ppi
826     100 ppi
827     112 ppi
828     141 ppi
829     100 ppi
830     141 ppi
831     100 ppi
832     141 ppi
833     112 ppi
834     112 ppi
835     112 ppi
836     141 ppi
837     141 ppi
838     112 ppi
839     157 ppi
840     141 ppi
841     141 ppi
842     135 ppi
843     141 ppi
844     141 ppi
845     100 ppi
846     141 ppi
847     141 ppi
848     112 ppi
849     100 ppi
850     141 ppi
851     135 ppi
852     135 ppi
853     100 ppi
854     112 ppi
855     227 ppi
856     100 ppi
857     141 ppi
858     141 ppi
859     112 ppi
860     100 ppi
861     157 ppi
862     100 ppi
863     100 ppi
864     127 ppi
865     141 ppi
866     141 ppi
867     141 ppi
868     157 ppi
869     157 ppi
870     157 ppi
871     242 ppi
872     141 ppi
873     141 ppi
874     242 ppi
875     100 ppi
876     141 ppi
877     141 ppi
878     141 ppi
879     100 ppi
880     100 ppi
881     141 ppi
882     100 ppi
883     141 ppi
884     157 ppi
885     141 ppi
886     141 ppi
887     157 ppi
888     100 ppi
889     141 ppi
890     100 ppi
891     141 ppi
892     141 ppi
893     157 ppi
894     141 ppi
895     100 ppi
896     141 ppi
897     141 ppi
898     157 ppi
899     141 ppi
900     100 ppi
901     157 ppi
902     141 ppi
903     147 ppi
904     135 ppi
905     141 ppi
906     157 ppi
907     141 ppi
908     141 ppi
909     157 ppi
910     100 ppi
911     112 ppi
912     100 ppi
913     112 ppi
914     176 ppi
915     141 ppi
916     100 ppi
917     141 ppi
918     157 ppi
919     141 ppi
920     135 ppi
921     135 ppi
922     141 ppi
923     100 ppi
924     157 ppi
925     141 ppi
926     157 ppi
927     141 ppi
928     127 ppi
929     141 ppi
930     141 ppi
931     100 ppi
932     141 ppi
933     112 ppi
934     135 ppi
935     157 ppi
936     141 ppi
937     141 ppi
938     157 ppi
939     157 ppi
940     100 ppi
941     141 ppi
942     141 ppi
943     141 ppi
944     137 ppi
945     141 ppi
946     141 ppi
947     135 ppi
948     157 ppi
949     157 ppi
950     141 ppi
951     157 ppi
952     157 ppi
953     141 ppi
954     141 ppi
955     157 ppi
956     157 ppi
957     141 ppi
958     141 ppi
959     141 ppi
960     157 ppi
961     141 ppi
962     141 ppi
963     141 ppi
964     141 ppi
965     141 ppi
966     141 ppi
967     141 ppi
968     255 ppi
969     141 ppi
970     141 ppi
971     100 ppi
972     141 ppi
973     141 ppi
974     100 ppi
975     100 ppi
976     141 ppi
977     141 ppi
978     141 ppi
979     141 ppi
980     141 ppi
981     100 ppi
982     141 ppi
983     100 ppi
984     100 ppi
985     141 ppi
986     141 ppi
987     157 ppi
988     127 ppi
989     141 ppi
990     141 ppi
991     141 ppi
992     157 ppi
993     157 ppi
994     141 ppi
995     166 ppi
996     141 ppi
997     141 ppi
998     100 ppi
999     135 ppi
1000    141 ppi
1001    156 ppi
1002    112 ppi
1003    137 ppi
1004    142 ppi
1005    161 ppi
1006    141 ppi
1007    142 ppi
1008    141 ppi
1009    142 ppi
1010    141 ppi
1011    157 ppi
1012    162 ppi
1013    225 ppi
1014    141 ppi
1015    141 ppi
1016    142 ppi
1017    141 ppi
1018    141 ppi
1019    141 ppi
1020    142 ppi
1021    142 ppi
1022    162 ppi
1023    142 ppi
1024    170 ppi
1025    162 ppi
1026    162 ppi
1027    162 ppi
1028    112 ppi
1029    162 ppi
1030    256 ppi
1031    100 ppi
1032    141 ppi
1033    162 ppi
1034    256 ppi
1035    162 ppi
1036    100 ppi
1037    157 ppi
1038    157 ppi
1039    162 ppi
1040    141 ppi
1041    162 ppi
1042    157 ppi
1043    162 ppi
1044    162 ppi
1045    157 ppi
1046    141 ppi
1047    157 ppi
1048    112 ppi
1049    145 ppi
1050    112 ppi
1051    162 ppi
1052    112 ppi
1053    112 ppi
1054    141 ppi
1055    112 ppi
1056    243 ppi
1057    162 ppi
1058    243 ppi
1059    243 ppi
1060    162 ppi
1061    162 ppi
1062    141 ppi
1063    162 ppi
1064    141 ppi
1065    162 ppi
1066    141 ppi
1067    243 ppi
1068    141 ppi
1069    141 ppi
1070    142 ppi
1071    141 ppi
1072    112 ppi
1073    189 ppi
1074    112 ppi
1075    189 ppi
1076    189 ppi
1077    141 ppi
1078    141 ppi
1079    142 ppi
1080    141 ppi
1081    141 ppi
1082    189 ppi
1083    162 ppi
1084    162 ppi
1085    162 ppi
1086    141 ppi
1087    189 ppi
1088    140 ppi
1089    157 ppi
1090    141 ppi
1091    141 ppi
1092    141 ppi
1093    141 ppi
1094    141 ppi
1095    141 ppi
1096    157 ppi
1097    157 ppi
1098    142 ppi
1099    141 ppi
1100    141 ppi
1101    141 ppi
1102    142 ppi
1103    142 ppi
1104    141 ppi
1105    170 ppi
1106    157 ppi
1107    157 ppi
1108    112 ppi
1109    112 ppi
1110    157 ppi
1111    157 ppi
1112    162 ppi
1113    112 ppi
1114    162 ppi
1115    170 ppi
1116    171 ppi
1117    157 ppi
1118    157 ppi
1119    157 ppi
1120    112 ppi
1121    112 ppi
1122    112 ppi
1123    157 ppi
1124    141 ppi
1125    100 ppi
1126    100 ppi
1127    157 ppi
1128    162 ppi
1129    157 ppi
1130    100 ppi
1131    157 ppi
1132    157 ppi
1133    141 ppi
1134    142 ppi
1135    157 ppi
1136    142 ppi
1137    142 ppi
1138    142 ppi
1139    142 ppi
1140    142 ppi
1141    142 ppi
1142    162 ppi
1143    141 ppi
1144    157 ppi
1145    141 ppi
1146    141 ppi
1147    162 ppi
1148    162 ppi
1149    141 ppi
1150    141 ppi
1151    162 ppi
1152    162 ppi
1153    142 ppi
1154    162 ppi
1155    201 ppi
1156    141 ppi
1157    142 ppi
1158    157 ppi
1159    142 ppi
1160    141 ppi
1161    141 ppi
1162    141 ppi
1163    157 ppi
1164    157 ppi
1165    170 ppi
1166    162 ppi
1167    157 ppi
1168    157 ppi
1169    112 ppi
1170    157 ppi
1171    166 ppi
1172    162 ppi
1173    166 ppi
1174    170 ppi
1175    141 ppi
1176    243 ppi
1177    141 ppi
1178    141 ppi
1179    141 ppi
1180    243 ppi
1181    252 ppi
1182    252 ppi
1183    252 ppi
1184    243 ppi
1185    141 ppi
1186    141 ppi
1187    157 ppi
1188    141 ppi
1189    157 ppi
1190    141 ppi
1191    157 ppi
1192    157 ppi
1193    162 ppi
1194    162 ppi
1195    112 ppi
1196    239 ppi
1197    157 ppi
1198    212 ppi
1199    141 ppi
1200    141 ppi
1201    227 ppi
1202    100 ppi
1203    141 ppi
1204    112 ppi
1205    141 ppi
1206    157 ppi
1207    227 ppi
1208    141 ppi
1209    243 ppi
1210    166 ppi
1211    141 ppi
1212    141 ppi
1213    157 ppi
1214    141 ppi
1215    141 ppi
1216    101 ppi
1217    112 ppi
1218    141 ppi
1219    100 ppi
1220    141 ppi
1221    141 ppi
1222    141 ppi
1223    142 ppi
1224    141 ppi
1225        NaN
1226    141 ppi
1227    157 ppi
1228    141 ppi
1229    141 ppi
1230    100 ppi
1231    141 ppi
1232    141 ppi
1233    157 ppi
1234    142 ppi
1235    141 ppi
1236    141 ppi
1237    141 ppi
1238    141 ppi
1239    141 ppi
1240    141 ppi
1241     91 ppi
1242    141 ppi
1243    141 ppi
1244    157 ppi
1245    137 ppi
1246    141 ppi
1247    141 ppi
1248    141 ppi
1249    112 ppi

In [427]:
df['Pixel Density']=df['Pixel Density'].fillna(df['Pixel Density'].mode()[0])

In [428]:
df['Pixel Density'] = df['Pixel Density'].str.extract(r'(\d+)').astype(int)

- Display Touchscreen

In [429]:
df['Display Touchscreen'].value_counts()

Display Touchscreen
No     7193
Yes     921
Name: count, dtype: int64

In [430]:
df['Display Touchscreen']=df['Display Touchscreen'].fillna('No')

- Clock-speed

In [431]:
df['Clock-speed']=df['Clock-speed'].fillna(df['Clock-speed'].mode()[0])

In [432]:
df['Clock-speed'] = df['Clock-speed'].str.extract(r'(\d+)').astype(int)

- Graphic Processor

In [433]:
df['Graphic Processor'].unique()

<StringArray>
[                       'Intel Iris X',             'NVIDIA GeForce RTX 4050',
                      'AMD Radeon 530',             'NVIDIA GeForce GTX 1050',
                          'AMD Radeon',           'Intel Integrated Graphics',
                   'Intel HD Graphics',             'NVIDIA GeForce RTX 3050',
                       'Intel UHD 620',                       'Intel Iris Xe',
 ...
                 'NVIDIA GeForce N16S',                    'ARM Mali-G52 MC2',
                'NVIDIA GEFORCE MX350',              'AMD Radeon Pro WX 3100',
 'NVIDIA Geforce RTX 2070 Super Max-Q',            'Intel Integrated Grphics',
             'NVIDIA Geforce GTX 2060',             'NVIDIA Geforce RTX 3000',
                   'AMD Radeon RX 550',               'NVIDIA Quadro RTX5000']
Length: 390, dtype: str

In [434]:
df['GPU_Brand'] = df['Graphic Processor'].str.extract(r'(Intel|NVIDIA|AMD|Apple|MediaTek|Microsoft)', expand=False)

In [435]:
df['GPU_Brand'].mode()[0]

'Intel'

In [436]:
df['GPU_Brand']=df['GPU_Brand'].fillna(df['GPU_Brand'].mode()[0])

In [437]:
def gpu_tier(gpu):
    gpu = str(gpu)

    if 'RTX 4050' in gpu or 'RTX 4060' in gpu or 'RTX 4070' in gpu:
        return 'High'

    elif 'RTX 3050' in gpu:
        return 'Mid'

    elif 'RTX 2050' in gpu:
        return 'Entry Gaming'

    elif 'GTX 1650' in gpu or 'GTX 1050' in gpu:
        return 'Entry Gaming'

    elif 'MX' in gpu:
        return 'Basic Dedicated'

    elif 'Intel' in gpu or 'Radeon' in gpu:
        return 'Integrated'

    elif 'Apple' in gpu:
        return 'Integrated'

    else:
        return 'Other'

df['GPU_Tier'] = df['Graphic Processor'].apply(gpu_tier)

In [438]:
df['GPU_Tier']

0            Integrated
1                  High
2            Integrated
3          Entry Gaming
4            Integrated
5            Integrated
6            Integrated
7            Integrated
8                   Mid
9            Integrated
10           Integrated
11           Integrated
12      Basic Dedicated
13         Entry Gaming
14           Integrated
15           Integrated
16         Entry Gaming
17           Integrated
18           Integrated
19           Integrated
20           Integrated
21           Integrated
22           Integrated
23           Integrated
24                Other
25           Integrated
26           Integrated
27         Entry Gaming
28         Entry Gaming
29         Entry Gaming
30         Entry Gaming
31           Integrated
32         Entry Gaming
33         Entry Gaming
34           Integrated
35           Integrated
36           Integrated
37           Integrated
38           Integrated
39           Integrated
40           Integrated
41           Integrated
42                  Mid
43                  Mid
44           Integrated
45           Integrated
46           Integrated
47      Basic Dedicated
48           Integrated
49                  Mid
50                  Mid
51           Integrated
52           Integrated
53           Integrated
54           Integrated
55                  Mid
56                  Mid
57                Other
58           Integrated
59           Integrated
60           Integrated
61                Other
62         Entry Gaming
63           Integrated
64           Integrated
65         Entry Gaming
66           Integrated
67      Basic Dedicated
68           Integrated
69           Integrated
70           Integrated
71           Integrated
72           Integrated
73           Integrated
74                Other
75           Integrated
76         Entry Gaming
77           Integrated
78      Basic Dedicated
79           Integrated
80           Integrated
81           Integrated
82           Integrated
83                  Mid
84           Integrated
85           Integrated
86                Other
87           Integrated
88           Integrated
89         Entry Gaming
90                  Mid
91           Integrated
92                  Mid
93           Integrated
94           Integrated
95         Entry Gaming
96           Integrated
97                  Mid
98           Integrated
99         Entry Gaming
100        Entry Gaming
101     Basic Dedicated
102          Integrated
103          Integrated
104                 Mid
105     Basic Dedicated
106                 Mid
107        Entry Gaming
108          Integrated
109          Integrated
110          Integrated
111          Integrated
112          Integrated
113     Basic Dedicated
114        Entry Gaming
115          Integrated
116          Integrated
117          Integrated
118          Integrated
119          Integrated
120          Integrated
121          Integrated
122          Integrated
123          Integrated
124          Integrated
125     Basic Dedicated
126        Entry Gaming
127               Other
128                 Mid
129        Entry Gaming
130          Integrated
131          Integrated
132                 Mid
133          Integrated
134               Other
135          Integrated
136          Integrated
137          Integrated
138          Integrated
139          Integrated
140          Integrated
141     Basic Dedicated
142          Integrated
143          Integrated
144          Integrated
145          Integrated
146               Other
147          Integrated
148        Entry Gaming
149          Integrated
150          Integrated
151          Integrated
152          Integrated
153          Integrated
154          Integrated
155          Integrated
156        Entry Gaming
157               Other
158        Entry Gaming
159          Integrated
160     Basic Dedicated
161     Basic Dedicated
162     Basic Dedicated
163          Integrated
164          Integrated
165          Integrated
166          Integrated
167          Integrated
168          Integrated
169          Integrated
170     Basic Dedicated
171          Integrated
172          Integrated
173          Integrated
174        Entry Gaming
175     Basic Dedicated
176        Entry Gaming
177          Integrated
178          Integrated
179          Integrated
180          Integrated
181          Integrated
182          Integrated
183          Integrated
184          Integrated
185        Entry Gaming
186          Integrated
187                 Mid
188     Basic Dedicated
189          Integrated
190          Integrated
191          Integrated
192          Integrated
193          Integrated
194                 Mid
195          Integrated
196          Integrated
197          Integrated
198          Integrated
199          Integrated
200          Integrated
201          Integrated
202          Integrated
203          Integrated
204          Integrated
205               Other
206          Integrated
207          Integrated
208          Integrated
209          Integrated
210          Integrated
211          Integrated
212          Integrated
213               Other
214        Entry Gaming
215          Integrated
216          Integrated
217               Other
218               Other
219          Integrated
220          Integrated
221          Integrated
222                High
223          Integrated
224          Integrated
225          Integrated
226               Other
227          Integrated
228          Integrated
229               Other
230          Integrated
231               Other
232          Integrated
233                 Mid
234          Integrated
235               Other
236          Integrated
237          Integrated
238          Integrated
239          Integrated
240          Integrated
241          Integrated
242          Integrated
243                 Mid
244               Other
245          Integrated
246          Integrated
247        Entry Gaming
248        Entry Gaming
249               Other
250          Integrated
251                 Mid
252          Integrated
253                 Mid
254               Other
255          Integrated
256        Entry Gaming
257          Integrated
258               Other
259          Integrated
260     Basic Dedicated
261               Other
262                 Mid
263          Integrated
264          Integrated
265          Integrated
266          Integrated
267          Integrated
268               Other
269               Other
270          Integrated
271          Integrated
272          Integrated
273          Integrated
274          Integrated
275               Other
276          Integrated
277          Integrated
278     Basic Dedicated
279          Integrated
280                 Mid
281               Other
282          Integrated
283          Integrated
284               Other
285               Other
286          Integrated
287          Integrated
288               Other
289               Other
290          Integrated
291               Other
292               Other
293          Integrated
294          Integrated
295          Integrated
296               Other
297          Integrated
298          Integrated
299          Integrated
300                 Mid
301          Integrated
302                 Mid
303          Integrated
304          Integrated
305               Other
306        Entry Gaming
307        Entry Gaming
308        Entry Gaming
309          Integrated
310               Other
311          Integrated
312     Basic Dedicated
313          Integrated
314                 Mid
315               Other
316          Integrated
317                High
318               Other
319                High
320          Integrated
321               Other
322          Integrated
323          Integrated
324          Integrated
325          Integrated
326               Other
327                 Mid
328               Other
329        Entry Gaming
330          Integrated
331               Other
332          Integrated
333        Entry Gaming
334          Integrated
335          Integrated
336                High
337          Integrated
338                High
339                 Mid
340     Basic Dedicated
341          Integrated
342          Integrated
343          Integrated
344               Other
345          Integrated
346                 Mid
347          Integrated
348          Integrated
349                 Mid
350               Other
351          Integrated
352               Other
353          Integrated
354          Integrated
355               Other
356                 Mid
357          Integrated
358          Integrated
359          Integrated
360                 Mid
361               Other
362                High
363          Integrated
364                High
365          Integrated
366          Integrated
367          Integrated
368                 Mid
369                 Mid
370        Entry Gaming
371               Other
372          Integrated
373          Integrated
374               Other
375          Integrated
376                High
377          Integrated
378          Integrated
379        Entry Gaming
380          Integrated
381          Integrated
382          Integrated
383          Integrated
384          Integrated
385          Integrated
386          Integrated
387          Integrated
388          Integrated
389          Integrated
390          Integrated
391          Integrated
392          Integrated
393                High
394          Integrated
395          Integrated
396          Integrated
397          Integrated
398          Integrated
399          Integrated
400          Integrated
401          Integrated
402          Integrated
403          Integrated
404        Entry Gaming
405     Basic Dedicated
406          Integrated
407          Integrated
408          Integrated
409          Integrated
410          Integrated
411          Integrated
412          Integrated
413        Entry Gaming
414          Integrated
415          Integrated
416          Integrated
417          Integrated
418          Integrated
419          Integrated
420          Integrated
421          Integrated
422               Other
423        Entry Gaming
424          Integrated
425          Integrated
426                 Mid
427          Integrated
428     Basic Dedicated
429          Integrated
430          Integrated
431        Entry Gaming
432        Entry Gaming
433        Entry Gaming
434        Entry Gaming
435          Integrated
436        Entry Gaming
437          Integrated
438          Integrated
439          Integrated
440          Integrated
441          Integrated
442          Integrated
443          Integrated
444        Entry Gaming
445          Integrated
446          Integrated
447        Entry Gaming
448     Basic Dedicated
449        Entry Gaming
450          Integrated
451          Integrated
452        Entry Gaming
453          Integrated
454          Integrated
455          Integrated
456          Integrated
457          Integrated
458          Integrated
459          Integrated
460          Integrated
461          Integrated
462          Integrated
463               Other
464          Integrated
465          Integrated
466          Integrated
467     Basic Dedicated
468          Integrated
469                 Mid
470     Basic Dedicated
471     Basic Dedicated
472          Integrated
473               Other
474          Integrated
475          Integrated
476                 Mid
477          Integrated
478          Integrated
479          Integrated
480          Integrated
481        Entry Gaming
482          Integrated
483        Entry Gaming
484        Entry Gaming
485          Integrated
486          Integrated
487          Integrated
488        Entry Gaming
489          Integrated
490          Integrated
491          Integrated
492        Entry Gaming
493        Entry Gaming
494          Integrated
495          Integrated
496          Integrated
497          Integrated
498          Integrated
499        Entry Gaming
500          Integrated
501                 Mid
502          Integrated
503          Integrated
504                 Mid
505          Integrated
506        Entry Gaming
507        Entry Gaming
508          Integrated
509          Integrated
510          Integrated
511        Entry Gaming
512          Integrated
513          Integrated
514          Integrated
515     Basic Dedicated
516          Integrated
517        Entry Gaming
518          Integrated
519        Entry Gaming
520          Integrated
521        Entry Gaming
522          Integrated
523               Other
524          Integrated
525          Integrated
526          Integrated
527          Integrated
528          Integrated
529               Other
530          Integrated
531          Integrated
532          Integrated
533          Integrated
534          Integrated
535               Other
536        Entry Gaming
537          Integrated
538               Other
539          Integrated
540          Integrated
541               Other
542          Integrated
543          Integrated
544          Integrated
545          Integrated
546          Integrated
547        Entry Gaming
548     Basic Dedicated
549          Integrated
550        Entry Gaming
551          Integrated
552          Integrated
553               Other
554          Integrated
555          Integrated
556          Integrated
557        Entry Gaming
558        Entry Gaming
559          Integrated
560          Integrated
561        Entry Gaming
562          Integrated
563          Integrated
564          Integrated
565          Integrated
566     Basic Dedicated
567        Entry Gaming
568          Integrated
569          Integrated
570          Integrated
571          Integrated
572          Integrated
573               Other
574          Integrated
575          Integrated
576          Integrated
577          Integrated
578        Entry Gaming
579        Entry Gaming
580          Integrated
581          Integrated
582        Entry Gaming
583          Integrated
584        Entry Gaming
585          Integrated
586          Integrated
587          Integrated
588                High
589                High
590          Integrated
591          Integrated
592          Integrated
593               Other
594          Integrated
595          Integrated
596          Integrated
597        Entry Gaming
598        Entry Gaming
599        Entry Gaming
600          Integrated
601          Integrated
602          Integrated
603          Integrated
604          Integrated
605               Other
606          Integrated
607                High
608          Integrated
609               Other
610          Integrated
611        Entry Gaming
612          Integrated
613          Integrated
614          Integrated
615                High
616          Integrated
617          Integrated
618          Integrated
619          Integrated
620          Integrated
621          Integrated
622          Integrated
623          Integrated
624        Entry Gaming
625          Integrated
626                High
627        Entry Gaming
628          Integrated
629          Integrated
630                High
631          Integrated
632          Integrated
633          Integrated
634        Entry Gaming
635                High
636          Integrated
637          Integrated
638          Integrated
639                 Mid
640               Other
641                 Mid
642          Integrated
643          Integrated
644          Integrated
645          Integrated
646          Integrated
647          Integrated
648          Integrated
649          Integrated
650          Integrated
651          Integrated
652          Integrated
653                High
654          Integrated
655          Integrated
656          Integrated
657          Integrated
658          Integrated
659                High
660          Integrated
661                High
662          Integrated
663          Integrated
664          Integrated
665          Integrated
666                 Mid
667        Entry Gaming
668          Integrated
669          Integrated
670          Integrated
671          Integrated
672          Integrated
673          Integrated
674          Integrated
675          Integrated
676          Integrated
677          Integrated
678                High
679                High
680          Integrated
681          Integrated
682          Integrated
683                High
684          Integrated
685                High
686                High
687          Integrated
688               Other
689                High
690                 Mid
691               Other
692               Other
693                High
694                High
695               Other
696               Other
697               Other
698          Integrated
699          Integrated
700                High
701          Integrated
702          Integrated
703          Integrated
704          Integrated
705          Integrated
706          Integrated
707          Integrated
708                 Mid
709          Integrated
710          Integrated
711          Integrated
712          Integrated
713                High
714                High
715                 Mid
716          Integrated
717          Integrated
718          Integrated
719          Integrated
720          Integrated
721          Integrated
722          Integrated
723          Integrated
724          Integrated
725          Integrated
726          Integrated
727          Integrated
728          Integrated
729          Integrated
730          Integrated
731          Integrated
732          Integrated
733          Integrated
734          Integrated
735          Integrated
736          Integrated
737               Other
738          Integrated
739          Integrated
740               Other
741        Entry Gaming
742          Integrated
743                High
744          Integrated
745          Integrated
746          Integrated
747          Integrated
748               Other
749          Integrated
750        Entry Gaming
751          Integrated
752          Integrated
753          Integrated
754          Integrated
755               Other
756                 Mid
757          Integrated
758               Other
759          Integrated
760                High
761                High
762                High
763          Integrated
764          Integrated
765          Integrated
766          Integrated
767          Integrated
768          Integrated
769          Integrated
770                High
771          Integrated
772          Integrated
773               Other
774          Integrated
775          Integrated
776          Integrated
777          Integrated
778          Integrated
779          Integrated
780          Integrated
781          Integrated
782          Integrated
783          Integrated
784          Integrated
785          Integrated
786          Integrated
787                High
788          Integrated
789                High
790          Integrated
791          Integrated
792                High
793                High
794          Integrated
795          Integrated
796          Integrated
797          Integrated
798          Integrated
799          Integrated
800          Integrated
801          Integrated
802          Integrated
803          Integrated
804          Integrated
805          Integrated
806          Integrated
807          Integrated
808          Integrated
809          Integrated
810          Integrated
811        Entry Gaming
812          Integrated
813          Integrated
814          Integrated
815        Entry Gaming
816          Integrated
817          Integrated
818          Integrated
819                 Mid
820          Integrated
821          Integrated
822          Integrated
823          Integrated
824          Integrated
825          Integrated
826          Integrated
827          Integrated
828          Integrated
829               Other
830          Integrated
831               Other
832          Integrated

In [439]:
df=df.drop('Graphic Processor',axis=1)

- RAM Type

In [440]:
df['RAM Type'].mode()

0    DDR4
Name: RAM Type, dtype: str

In [441]:
df['RAM Type'] = df['RAM Type'].str.extract(r'(DDR[345])')

In [442]:
df['RAM Type']=df['RAM Type'].fillna(df['RAM Type'].mode()[0])

- SSD Capacity

In [443]:
df['SSD Capacity'].unique()

<StringArray>
['512 GB',      nan, '256 GB',  '32 GB',   '1 TB', '128 GB',  '16 GB',
  '64 GB',    '256',   '8 GB',   '4 TB',   '2 TB',    '512',      '1',
 '360 GB',   '1 GB']
Length: 16, dtype: str

In [444]:
df['SSD Capacity']=df['SSD Capacity'].fillna(df['SSD Capacity'].mode()[0])

In [445]:
def storage_to_gb(x):
    if pd.isna(x):
        return None

    x = str(x).upper().strip()

    if 'TB' in x:
        return float(x.replace('TB', '').strip()) * 1024
    elif 'GB' in x:
        return float(x.replace('GB', '').strip())
    else:
        return float(x)

temp = df['SSD Capacity'].apply(storage_to_gb)

df = df[temp >= 256]
df['SSD Capacity'] = df['SSD Capacity'].replace({
    '256': '256 GB',
    '512': '512 GB'
})

- Battery Type

In [446]:
df['Battery Type'].value_counts()

Battery Type
Li-Ion    6221
Li-Po      938
Name: count, dtype: int64

In [447]:
df['Battery Type']=df['Battery Type'].fillna(df['Battery Type'].mode()[0])

- Wi-Fi Version

In [448]:
df['Wi-Fi Version'].unique()

array([ 6.,  5.,  4., nan,  7.])

In [449]:
df['Wi-Fi Version']= df['Wi-Fi Version'].fillna(df['Wi-Fi Version'].mode()[0])

In [450]:
df.isnull().sum()

Brand                    0
Model                    0
Weight                   0
Operating System         0
Display Size             0
Pixel Density            0
Display Touchscreen      0
Processor                0
Clock-speed              0
Capacity                 0
RAM Type                 0
SSD Capacity             0
Battery Type             0
Wi-Fi Version            0
Warranty               448
Price (Rs)              21
Weight_Category          0
Resolution_X             0
Resolution_Y             0
GPU_Brand                0
GPU_Tier                 0
dtype: int64

- Warranty

In [451]:
df['Warranty'].value_counts()

Warranty
1 Year      6701
2 Years      408
3 Years      283
1             21
2 Year         8
1 Years        7
3 Year         4
4 Years        1
4              1
8 Years        1
10 Years       1
12 Years       1
1.5 Year       1
Name: count, dtype: int64

In [452]:
df['Warranty']= df['Warranty'].fillna(df['Warranty'].mode()[0])

In [453]:
# Extract the numeric part
df['Warranty'] = df['Warranty'].astype(str).str.extract(r'(\d+\.?\d*)')

# Convert to numeric
df['Warranty'] = pd.to_numeric(df['Warranty'], errors='coerce')

# Keep only 1, 2, and 3 years
df = df[df['Warranty'].isin([1, 2, 3])]

In [454]:
df['Warranty'] = df['Warranty'].astype(int)

In [455]:
df=df.dropna()

In [456]:
df.select_dtypes(include='number').corr()

,Weight,Display Size,Pixel Density,Clock-speed,Wi-Fi Version,Warranty,Price (Rs),Resolution_X,Resolution_Y
Weight,1.000000,0.703246,-0.225768,0.067525,-0.036246,0.015809,0.279842,0.004614,-0.031743
Display Size,0.703246,1.000000,-0.290361,0.112267,0.019206,-0.016917,0.148156,0.027480,-0.015652
Pixel Density,-0.225768,-0.290361,1.000000,0.242919,0.337650,0.060491,0.510329,0.942684,0.950827
Clock-speed,0.067525,0.112267,0.242919,1.000000,0.471460,0.149928,0.301564,0.281820,0.314880
Wi-Fi Version,-0.036246,0.019206,0.337650,0.471460,1.000000,0.143219,0.343127,0.351626,0.374742
Warranty,0.015809,-0.016917,0.060491,0.149928,0.143219,1.000000,0.209930,0.055850,0.075598
Price (Rs),0.279842,0.148156,0.510329,0.301564,0.343127,0.209930,1.000000,0.582470,0.597406
Resolution_X,0.004614,0.027480,0.942684,0.281820,0.351626,0.055850,0.582470,1.000000,0.979053
Resolution_Y,-0.031743,-0.015652,0.950827,0.314880,0.374742,0.075598,0.597406,0.979053,1.000000

- os

In [457]:
df['Operating System'].value_counts()

Operating System
Windows 11 Home Basic        3684
Windows 10 Home Basic        2627
DOS                           375
Windows 11 Professional       332
Windows 10 Professional       181
Windows 11                    156
Windows 10                    116
macOS Sequoia                  66
Google Chrome                  61
Windows 8.1                    49
Linux                          44
macOS Sonoma                   40
macOS Ventura                  17
Google Chrome Home Basic       15
macOS Mojave                   14
Ubuntu                         11
macOS Catalina                 10
DOS Professional               10
macOS Monterey                  9
macOS Big Sur                   7
macOS High Sierra               6
DOS Home Basic                  5
Windows 11 Home Premium         5
macOS Sierra                    4
Windows 8.1 Professional        3
macOS Monterey Home Basic       2
Windows 8                       2
Prime OS Home Basic             2
Windows 10 Home Premium         2
Jio OS                          2
MAC OS X El Capitan             1
Home Basic                      1
Name: count, dtype: int64

In [458]:
def clean_os(os):
    os = str(os).lower()

    if 'windows 10' in os:
        return 'Windows 10'
    elif 'windows 11' in os:
        return 'Windows 11'
    elif 'windows 8' in os:
        return 'Windows 8'
    elif 'macos' in os or 'mac os x' in os:
        return 'macOS'
    elif 'linux' in os or 'ubuntu' in os:
        return 'Linux'
    elif 'dos' in os:
        return 'DOS'
    elif 'chrome' in os:
        return 'Chrome OS'
    else:
        return 'Other'

df['Operating System'] = df['Operating System'].apply(clean_os)

- Processor

In [459]:
df['Processor'].value_counts()

Processor
Intel Core i5-1135G7 (11th Gen)             377
Intel Core i3-1115G4 (11th Gen)             279
Intel Core i5-1235U (12th Gen)              219
Intel Core i3-1005G1 (10th Gen)             191
Intel Core i5-8250U (8th Gen)               136
Intel Core i3-1215U (12th Gen)              133
Intel Core i5-12450H (12th Gen)             132
Intel Core i5-10210U (10th Gen)             124
Intel Core i5-1035G1 (10th Gen)             123
Intel Core i7-1165G7 (11th Gen)             118
Intel Core i5-1335U (13th Gen)              112
Intel Core Ultra 7 - 155H                   111
Intel Core i7-10750H (10th Gen)             107
Intel Core i7-12700H (12th Gen)             102
Intel Core i5-8265U (8th Gen)               101
Intel Core i3-7020U (7th Gen)                94
Intel Core i3-10110U (10th Gen)              77
AMD Hexa Core Ryzen 5 - 5600H                75
Intel Core i7-1255U (12th Gen)               75
Intel Core i7-9750H (9th Gen)                71
Intel Core i5-7200U (7th Gen)                69
Intel Core i3-6006U (6th Gen)                69
Intel Core i7-11800H (11th Gen)              68
Intel Core i5-10300H (10th Gen)              68
Intel Core i5-12500H (12th Gen)              67
Intel Core i7-1355U (13th Gen)               63
Intel Core i5-9300H (9th Gen)                62
AMD Quad Core Ryzen 5 3500U                  61
Intel Core i7-12650H (12th Gen)              61
Intel Core i5-13420H (13th Gen)              59
Intel Core i5-11400H (11th Gen)              58
Intel Core Ultra 5 - 125H                    58
Intel Core i5-1240P (12th Gen)               56
AMD Hexa Core Ryzen 5 - 7530U                54
Intel Core i7-13700H (13th Gen)              54
AMD Hexa Core Ryzen 5 - 5500U                54
Intel Core i7-10510U (10th Gen)              53
Intel Core i7-13620H (13th Gen)              47
Intel Core Ultra 9 - 185H                    47
AMD Dual Core Ryzen 3 3250U                  44
Apple M3                                     43
Intel Core i7-8550U (8th Gen)                42
Intel Core i3-8130U (8th Gen)                42
Intel Core i5-1155G7 (11th Gen)              42
Intel Core i9-13900H (13th Gen)              41
Intel Core i5-13500H (13th Gen)              40
AMD Octa Core Ryzen 7 - 6800H                39
AMD Quad Core Ryzen 3 - 7320U                39
Intel Core i7-1360P (13th Gen)               39
AMD Hexa Core Ryzen 5 5500U                  38
AMD Octa Core Ryzen 7 - 5800H                38
Intel Core i7-8750H (8th Gen)                38
Intel Core i7-13700HX (13th Gen)             36
AMD Octa Core Ryzen 7 - 7730U                36
Intel Core i3-1315U (13th Gen)               36
Intel Core i5-11300H (11th Gen)              34
AMD Dual Core Ryzen 3-3250U                  34
AMD Hexa Core Ryzen 5 4600H                  33
Intel Core i7-8565U (8th Gen)                32
Intel Core i3-7100U (7th Gen)                31
AMD Quad Core Ryzen 5 - 7520U                31
Intel Core i5 - 13420H (13th Gen)            31
Intel Core i7-7700HQ (7th Gen)               30
AMD Hexa Core Ryzen 5 - 5625U                30
Intel Core i3-N305 (12th Gen)                30
Apple M4                                     30
Intel Core i7-13650HX (13th Gen)             30
Intel Core i9-14900HX (14th Gen)             30
Intel Celeron Dual Core - N4500              29
AMD Octa Core Ryzen 7 - 5700U                29
Intel Core i7-1260P (12th Gen)               29
Intel Core i9-12900H (12th Gen)              28
Intel Core i3-8145U (8th Gen)                28
Intel Core Ultra 7 - 155U                    28
Intel Core i5-11320H (11th Gen)              27
Intel Core 5 - 120U (Series 1)               27
AMD Octa Core Ryzen 9 5900HX                 27
Intel Core i7-10870H (10th Gen)              27
AMD Octa Core Ryzen 7 4800H                  27
Intel Core i3-1125G4 (11th Gen)              26
AMD Hexa Core Ryzen 5 - 7535HS               26
Intel Core i5 - 1334U (13th Gen)             26
AMD Octa Core Ryzen 7 - 7840HS               26
AMD Octa Core Ryzen 7 5800H                  25
Intel Core i5-1340P (13th Gen)               24
Intel Core i3-1305U (13th Gen)               24
Intel Core i7-1065G7 (10th Gen)              23
Intel Core i7-7500U (7th Gen)                23
Intel Core i5- 8250U (8th Gen)               22
AMD Dual Core A6-9225                        22
AMD Octa Core Ryzen 7 - 6800HS               22
AMD Hexa Core Ryzen 5 4500U                  21
AMD Octa Core Ryzen 9 5900HS                 21
Intel Core i5 - 12450H (12th Gen)            21
Intel Core i7-14700HX (14th Gen)             21
Intel Core i5-11260H (11th Gen)              20
Intel Core i7-10875H (10th Gen)              20
AMD Quad Core Ryzen 5-7520U                  20
AMD Quad Core Ryzen 5 3550H                  20
AMD Octa Core Ryzen 9 - 7940HS               20
Intel Core i7-11370H (11th Gen)              20
AMD Hexa Core Ryzen 5 5600H                  19
AMD Octa Core Ryzen 7 - 7735HS               19
Intel Core Ultra 7 - 258V (Series 2)         19
AMD Quad Core Ryzen 3 - 5300U                19
Intel Celeron Dual Core - N4020              19
Intel Celeron Dual Core N4020                18
Apple M2                                     18
Intel Core i5-6200U (6th Gen)                18
Intel Core i9-13900HX (13th Gen)             18
Intel Core Ultra 5 - 125U                    18
Intel Core i7 - 13620H (13th Gen)            18
Intel Core i3 - 1315U (13th Gen)             18
Intel Core i5-1334U (13th Gen)               18
Intel Core i5-13450HX (13th Gen)             17
AMD Dual Core Athlon 3050U                   16
Intel Core i5-12450HX (12th Gen)             16
AMD Octa Core Ryzen 7-5800H                  15
AMD Dual Core Ryzen 3 - 3250U                15
Intel Core i5 - 1335U (13th Gen)             15
AMD Octa Core Ryzen 7 - 4800H                15
Intel Core i5-8300H (8th Gen)                15
Intel Core 7 - 150U (Series 1)               15
Intel Core i7-1195G7 (11th Gen)              15
AMD Octa Core Ryzen 7 - 7435HS               15
AMD Octa Core Ryzen 9 - 6900HS               15
Intel Celeron Dual Core- N4020               14
AMD Dual Core Ryzen 3 3200U                  14
Intel Core i9-13980HX (13th Gen)             14
Intel Core i5 - 1235U (12th Gen)             14
AMD Octa Core Ryzen 7 - 8845HS               14
AMD Octa Core Ryzen 9 - 6900HX               14
AMD Quad Core Ryzen 7 3750H                  13
Intel Core i3-5005U (5th Gen)                13
Intel Pentium Quad Core N4200                13
Intel Core Ultra 7 - 256V (Series 2)         13
AMD Quad-Core Ryzen 5 - 7520U                13
AMD Octa Core Ryzen 7 5700U                  13
AMD Dual Core A9-9425                        13
Intel Core i3 - 1215U (12th Gen)             12
AMD Ryzen 5 Quad Core 2500U                  12
Intel Celeron Dual Core- N4500               12
AMD Octa Core Ryzen 7 4700U                  12
Intel Core i9-11900H (11th Gen)              12
Intel Core i5-5200U (5th Gen)                11
AMD Octa Core Ryzen 7 5800HS                 11
Intel Pentium Quad Core N5000                11
Qualcomm Snapdragon X Elite                  11
Intel Core i5-7300HQ (7th Gen)               10
Intel Core i3-1220P (12th Gen)               10
Intel Core i3-6100U (6th Gen)                10
AMD Octa Core Ryzen 9-5900HX                 10
AMD Octa Core Ryzen 7 - 5800HS               10
AMD Octa Core Ryzen 7-6800H                   9
Intel Pentium Quad Core N5030                 9
AMD Dual Core E2-9000                         9
Intel Celeron Dual Core N3060                 9
Intel Pentium Quad Core N3710                 9
Intel Core i5 - 13450HX (13th Gen)            9
Intel Core Ultra 5 - 226V (Series 2)          9
AMD Dual Core Athlon - 3050U                  9
Intel Celeron Dual Core N4000                 9
AMD Octa Core Ryzen 7 4800HS                  9
Intel Core i9-10980HK (10th Gen)              9
AMD Hexa Core Ryzen 5 - 4600H                 8
AMD Quad Core Ryzen 5 2500U                   8
AMD Dual Core A4-9125                         8
AMD Hexa Core Ryzen 5-5600H                   8
AMD Dual Core A9-9420                         8
Intel Core i7 - 1355U (13th Gen)              8
Intel Core i7 - 13650HX (13th Gen)            8
Intel Celeron Dual-Core - N4500               8
AMD Quad Core Ryzen 3 - 7330U                 8
Intel Core i3-7130U (7th Gen)                 8
Intel Core i7-14650HX (14th Gen)              8
Intel Celeron Dual Core N3350                 8
AMD Hexa Core Ryzen 5 5600U                   8
Apple M4 Pro                                  8
Apple M3 Pro                                  8
Intel Core i5-1230U (12th Gen)                8
Intel Core i5-10500H (10th Gen)               7
Apple M1                                      7
Intel Pentium Dual Core 4417U                 7
Intel Core i5-4200U (4th Gen)                 7
Intel Pentium Quad-Core N3710                 7
AMD Octa Core Ryzen 9 - 5900HX                7
Intel Core i3-5010U (5th Gen)                 7
Intel Core i5-7Y54 (7th Gen)                  7
AMD Quad Core Ryzen 5-3450U                   7
AMD Dual Core A6 9220                         7
Intel Core i3 - 1305U (13th Gen)              7
AMD Hexa-Core Ryzen 5 - 5625U                 7
AMD Hexa-Core Ryzen 5 - 7530U                 7
AMD Hexa Core Ryzen 5 - 6600H                 7
AMD Hexa Core Ryzen 5-5500U                   7
AMD Octa Core Ryzen 7 - 5800U                 7
AMD Octa Core Ryzen 7 - 7735U                 7
Intel Core i7-8650U (8th Gen)                 7
Apple M2 Pro                                  7
AMD Quad-Core A8-7410                         6
AMD Quad Core Ryzen 5 3450U                   6
Intel Core i5-8210Y (8th Gen)                 6
Intel Core i7-1185G7 (11th Gen)               6
AMD Dodeca Core Ryzen 9 - HX 370              6
Intel Core i7-1250U (12th Gen)                6
AMD Hexa Core Ryzen 5 - 7430U                 6
AMD Octa-Core Ryzen 7 - 7735HS                6
AMD Quad-Core Ryzen 3 - 7320U                 6
Intel Core i7 - 14650HX (14th Gen)            6
Intel Core Ultra 7 - 165U                     6
AMD Hexa-Core Ryzen 5 - 5600H                 6
AMD Hexa-Core Ryzen 5 - 5500U                 6
Intel Core i5-13500HX (13th Gen)              6
Intel Core i5-10200H (10th Gen)               6
Intel Core i5 - 13500H (13th Gen)             6
Apple M4 Max                                  6
Qualcomm Snapdragon X Plus                    6
AMD Octa Core Ryzen 9 - 8945HS                6
Intel Celeron Dual Core - N3350               6
AMD Octa Core Ryzen 7 5800U                   6
Apple M3 Max                                  6
Intel Core i3-4010U (4th Gen)                 5
Intel Core Ultra 9 - 285H (Series 2)          5
AMD Octa Core Ryzen 7 - 5825U                 5
Intel Core i7 - 14700HX (14th Gen)            5
Intel Core i5 - 12450HX (12th Gen)            5
AMD Octa-Core Ryzen 7 - 5700U                 5
AMD Octa-Core Ryzen 7 - 7730U                 5
Intel Core i9 - 13900H (13th Gen)             5
Intel Core i3 - 1115G4 (11th Gen)             5
AMD Octa-Core Ryzen 7 - 8840HS                5
Intel Core i5 (10th Gen)                      5
Intel Core i9-13950HX (13th Gen)              5
Intel Pentium Dual Core 5405U                 5
Intel Pentium Silver - N6000                  5
AMD Dual Core Ryzen 3 2200U                   5
Intel Core i5-1035G4 (10th Gen)               5
Intel Core i9-9880H (9th Gen)                 5
Intel Core Ultra 5 - 225H (Series 2)          5
Intel Core 5 - 210H (Series 2)                5
AMD Octa Core Ryzen 7 - 7840U                 5
AMD Hexa Core Ryzen 5 - 5600U                 5
AMD Octa Core Ryzen 9 4900HS                  5
Intel Pentium Gold - 7505                     5
Intel Core i3-1215U                           4
AMD Quad Core Ryzen 5 - 5500H                 4
Intel Core i3-4005U                           4
AMD Quad Core Ryzen 3 4300U                   4
Intel Core i3-4030U                           4
Intel Core i3-3217U (3rd Gen)                 4
Intel Core i5-4210U                           4
AMD Hexa Core Ryzen 5 - 7640HS                4
Intel Pentium Quad-Core N3700                 4
AMD Octa Core Ryzen AI 7 - 350                4
Intel Core i7 - 1255U (12th Gen)              4
AMD Octa-Core Ryzen 7 - 8845HS                4
Qualcomm Snapdragon X Plus X1P-42-100         4
MediaTek Octa Core MT8183                     4
AMD Quad-Core E2-7110                         4
AMD Quad Core Ryzen 3 5300U                   4
Intel Core i7-1365U (13th Gen)                4
AMD Hexadeca-Core Ryzen 9 - 7945HX            4
Intel Core 3 - 100U (Series 1)                4
AMD Dual Core Ryzen 3-3200U                   4
AMD Octa Core Ryzen 7-4800H                   4
Intel Pentium Dual Core 4415U                 4
Intel Core i3-1035G1 (10th Gen)               4
Intel Core i7-6700HQ (6th Gen)                4
AMD Dual Core Athlon 300U                     4
Intel Core i5-7300U (7th Gen)                 4
AMD Quad Core Ryzen 7 3700U                   4
Intel Core i7 - 12650H (12th Gen)             4
Qualcomm Snapdragon X Elite X1E-78-100        4
Intel Core i9-12900HK (12th Gen)              4
Intel Core i5-8257U (8th Gen)                 4
Qualcomm Snapdragon X X1 26 100               4
Intel Core 7 - 240H (Series 2)                4
AMD Octa Core Ryzen 7-5800HS                  4
AMD Quad Core Ryzen 3-5425U                   4
Intel Celeron Quad Core - N4120               4
AMD Dual Core A6 9225                         3
AMD Ryzen 3 Dual Core -2200U                  3
Intel Core i7-5500U (5th Gen)                 3
Intel Celeron Dual-Core N3050                 3
Intel Core i5 - 12500H (12th Gen)             3
MediaTek Kompanio 520                         3
AMD Hexa Core Ryzen 5 4600HS                  3
AMD Hexa Core Ryzen 5 - 8645HS                3
AMD Dual Core Athlon-3050U                    3
Intel Core i7 8550U (8th Gen)                 3
Intel Core i5-9300HF (9th Gen)                3
Apple M1 Pro                                  3
AMD Quad Core Ryzen 5 - 3500U                 3
AMD Dual Core Athlon 3020e                    3
Qualcomm Snapdragon X Plus X1P-64-100         3
AMD Dodeca Core Ryzen AI 9 HX - 370           3
AMD Hexa-Core Ryzen 5 - 7535HS                3
AMD Octa-Core Ryzen 7 - 7735U                 3
AMD Hexa-Core Ryzen 5 - 7535U                 3
AMD Quad-Core Ryzen 3 - 5300U                 3
Intel Core i7 - 13700H (13th Gen)             3
AMD Quad core Ryzen 5 3500U                   3
Intel Core Ultra 5 - 135U                     3
Intel Core i5-1345U (13th Gen)                3
AMD Dual Core E2-9000E                        3
AMD Hexa Core Ryzen 5 - 7535U                 3
Intel Pentium Silver N6000                    3
AMD Dual Core Athlon 3150U                    3
AMD Quad Core Ryzen 5-3500U                   3
Intel Core i7-9850H (9th Gen)                 3
Intel Core i3-1115G4                          3
Intel Celeron Dual-Core - N4020               3
AMD Octa Core Ryzen 9-5900HS                  3
Intel Core i7-7660U (7th Gen)                 3
AMD Deca-Core Ryzen 9 - 365                   3
Qualcomm Snapdragon X Plus - X1P 42 100       3
Intel Core i7-1280P (12th Gen)                3
Intel Core i7-12800H (12th Gen)               3
AMD Octa Core Ryzen 7 - 7745HX                3
AMD Ryzen 7-6800H                             3
Qualcomm Snapdragon X Elite X1E 78 100        3
AMD Octa Core Ryzen 9 - 5900HS                3
Apple M2 Max                                  3
Intel Core i5-1135G7                          3
Intel Celeron Dual Core 3867U                 3
Intel Core i9-9980HK (9th Gen)                3
Intel Core i3-7100U                           3
Intel Core i5-8259U (8th Gen)                 3
AMD Hexa Core Ryzen 5-5625U                   3
AMD Ryzen 7 5800H                             3
Intel Core i3 (11th Gen)                      3
Intel Core i9-8950HK (8th Gen)                3
Intel Core i9-12900HX (12th Gen)              3
AMD Octa Core Ryzen 7 - 6800U                 3
AMD Dual Core E2-9000e                        2
Intel Core i7 (10th Gen)                      2
Intel Core i5-1038NG7 (10th Gen)              2
Intel Core i3-1115G4 (10th Gen)               2
AMD Hexa Core Ryzen 5 - 5600HS                2
Intel Celeron Quad Core N2930                 2
Intel Core i7-8500Y (8th Gen)                 2
Intel Core i7-4510U                           2
Intel Core i3-3110M (3rd Gen)                 2
Intel Pentium Quad Core N3530                 2
AMD Hexadeca Core Ryzen 9 - 7945HX            2
Intel Core i7-11600H (11th Gen)               2
Intel Core i7-4510U (4th Gen)                 2
Intel Core Ultra 9 - 288V (Series 2)          2
AMD Hexa Core Ryzen 5-4600H                   2
Intel Celeron Dual Core-N4020                 2
AMD Dodeca Core Ryzen AI 9 HX - 375           2
AMD Octa Core Ryzen AI 7 PRO - 360            2
Intel Core Ultra 7 - 268V (Series 2)          2
Intel Core i5 - 1135G7 (11th Gen)             2
AMD Quad-Core Ryzen 3 - 7335U                 2
Intel Core i3 - 1215U                         2
Intel Core Ultra 7 - 165H                     2
MediaTek MT8788                               2
AMD Dual Core Athlon - 7120U                  2
AMD Hexa-Core Ryzen 5 - 7430U                 2
Intel Core i9 - 13900HX (13th Gen)            2
AMD Quad Core Ryzen 3-5300U                   2
Intel Celeron Dual-Core N3060                 2
Intel Core i9 - 13980HX (13th Gen)            2
Intel Core i7-11850H (11th Gen)               2
AMD Quad-Core A10-9600P                       2
AMD Quad Core A8-6410                         2
Intel Core i5-1005G1 (10th Gen)               2
AMD Octa Core Ryzen 7-5825U                   2
Intel Core i9-12900H                          2
Intel Core i5-1235UG4 (12th Gen)              2
Intel Pentium Silver - N5030                  2
Intel Core i7-9750HF (9th Gen)                2
APU Quad Core A12-9720P                       2
AMD Hexa Core Ryzen 5-5600U                   2
AMD Hexa Core Ryzen 5 - 8540U                 2
AMD Octa Core Ryzen 7 - 8840U                 2
Qualcomm Snapdragon X Elite - X1E-80-100      2
Intel Pentium Quad Core - N100                2
Intel Core i9-11980HK (11th Gen)              2
Intel Pentium Quad Core - N5030               2
AMD Dual Core Athlon - 3020e                  2
Intel Core i7-12650H                          2
AMD Dual Core A9-9225                         2
Intel Core i3 (10th Gen)                      2
AMD Dual Core 3020e                           2
Intel Core i9-13900HK (13th Gen)              2
AMD Octa Core Ryzen 9 - 8945H                 2
Intel Core i5-1235U (13th Gen)                2
AMD Dual Core A6-9200                         2
AMD Ryzen 5 Quad Core 3550H                   2
Intel Core i5-1035G1 (1st Gen)                2
Intel Core i5-1035G7 (10th Gen)               2
Intel Core i7-7820HK (7th Gen)                2
AMD Quad Core Ryzen 5 - 7235HS                2
Intel Core Ultra 7 - 255H (Series 2)          2
Intel Core i7 - 1165G7 (11th Gen)             2
Intel Core i5-1115G4 (11th Gen)               2
Intel Core i5-8305G (8th Gen)                 2
AMD Octa Core Ryzen 7-5700U                   2
AMD Dual-Core A9-9420                         2
Intel Core i7-6500U (6th Gen)                 2
AMD Hexa Core Ryzen 5 - 4680U                 2
Intel Core i5-1155G7                          2
Intel Core i5-8279U (8th Gen)                 2
Intel Core i3-1135G7 (11th Gen)               2
AMD Quad-Core A12 9720P                       2
AMD Athlon Dual Core - 3050U                  2
Intel Core m3-8100Y (8th Gen)                 2
Intel Core i7-11390H (11th Gen)               2
AMD Quad Core Ryzen 3-3250U                   2
Intel Core i5-12450H                          2
AMD Dual Core A4-9120e                        2
Intel Core i7-1255U                           2
AMD Hexa Core Ryzen 5 - 5650U                 2
Intel Core i5-1035G1 (11th Gen)               2

In [460]:
def cpu_brand(cpu):
    cpu = str(cpu)

    if 'Intel' in cpu:
        return 'Intel'
    elif 'AMD' in cpu:
        return 'AMD'
    elif 'Apple' in cpu:
        return 'Apple'
    elif 'Qualcomm' in cpu:
        return 'Qualcomm'
    elif 'MediaTek' in cpu:
        return 'MediaTek'
    else:
        return 'Other'

df['CPU_Brand'] = df['Processor'].apply(cpu_brand)

In [461]:
df['CPU_Brand'].unique()

<StringArray>
['Intel', 'AMD', 'Apple', 'MediaTek', 'Qualcomm', 'Other']
Length: 6, dtype: str

In [462]:
import re

def cpu_category(cpu):
    cpu = str(cpu)

    # Apple
    if 'M1' in cpu:
        return 'Apple M1'
    elif 'M2' in cpu:
        return 'Apple M2'
    elif 'M3' in cpu:
        return 'Apple M3'
    elif 'M4' in cpu:
        return 'Apple M4'

    # Core Ultra
    ultra = re.search(r'Ultra\s+([579])', cpu)
    if ultra:
        return f'Ultra {ultra.group(1)}'

    # Intel
    intel = re.search(r'i([3579])[-\s]?(\d{4,5})', cpu)

    if intel:
        family = f'i{intel.group(1)}'
        model = intel.group(2)

        if len(model) == 4:      # 8250U, 9750H
            gen = model[0]
        else:                    # 12450H, 13420H
            gen = model[:2]

        return f'{family}-{gen}Gen'

    # AMD
    amd = re.search(r'Ryzen\s+([3579])\s+(\d{4})', cpu)

    if amd:
        family = f'Ryzen {amd.group(1)}'
        gen = amd.group(2)[0]

        return f'{family}-{gen}Gen'

    return 'Other'

df['CPU_Category'] = df['Processor'].apply(cpu_category)

In [463]:
df['CPU_Category'].unique()

<StringArray>
[     'i5-1Gen',     'i7-13Gen',      'i5-8Gen',      'i7-7Gen',
        'Other', 'Ryzen 5-4Gen',     'i5-10Gen',     'i3-10Gen',
      'i5-7Gen', 'Ryzen 5-5Gen', 'Ryzen 7-5Gen',      'i3-1Gen',
     'i5-11Gen',     'i7-10Gen', 'Ryzen 5-3Gen',     'i7-11Gen',
      'i7-8Gen', 'Ryzen 3-3Gen',     'i5-12Gen',     'Apple M3',
 'Ryzen 7-3Gen',      'i3-7Gen',      'i7-1Gen',      'i7-9Gen',
      'i3-8Gen', 'Ryzen 5-2Gen',      'i3-4Gen',     'Apple M1',
     'i9-13Gen',     'Apple M2', 'Ryzen 3-4Gen',      'i3-6Gen',
      'i5-4Gen',      'i3-5Gen',      'i3-3Gen',      'i7-4Gen',
      'i5-5Gen',      'Ultra 5',      'i5-6Gen',     'i5-13Gen',
      'i7-5Gen', 'Ryzen 9-5Gen',     'i7-12Gen',      'i5-2Gen',
     'i9-12Gen', 'Ryzen 7-4Gen',      'Ultra 7',      'Ultra 9',
      'i5-9Gen',     'Apple M4', 'Ryzen 3-5Gen',     'i7-14Gen',
     'i9-14Gen',     'i9-11Gen', 'Ryzen 3-2Gen',      'i7-6Gen',
      'i9-9Gen', 'Ryzen 7-6Gen',     'i5-14Gen',     'i9-10Gen',
 'Ryzen 9-4Gen',      'i9-8Gen']
Length: 62, dtype: str

In [464]:
df.isnull().sum()

Brand                  0
Model                  0
Weight                 0
Operating System       0
Display Size           0
Pixel Density          0
Display Touchscreen    0
Processor              0
Clock-speed            0
Capacity               0
RAM Type               0
SSD Capacity           0
Battery Type           0
Wi-Fi Version          0
Warranty               0
Price (Rs)             0
Weight_Category        0
Resolution_X           0
Resolution_Y           0
GPU_Brand              0
GPU_Tier               0
CPU_Brand              0
CPU_Category           0
dtype: int64

In [465]:
df=df.drop('Processor',axis=1)

In [466]:
df = df[df['Price (Rs)'] <= 150000]

In [467]:
df['Total_Pixels'] = df['Resolution_X'] * df['Resolution_Y']

In [468]:
def screen_category(size):
    if size < 14:
        return 'Small'
    elif size <= 15.6:
        return 'Medium'
    else:
        return 'Large'

df['Screen_Category'] = df['Display Size'].apply(screen_category)

In [469]:
def ppi_category(ppi):
    if ppi < 140:
        return 'Low'
    elif ppi < 180:
        return 'Medium'
    else:
        return 'High'

df['PPI_Category'] = df['Pixel Density'].apply(ppi_category)

In [470]:
df=df.dropna()

In [471]:
df.shape

(7061, 25)

In [472]:
df.to_csv('cleaned_data.csv')

In [473]:
df.select_dtypes(include="number").corr()

,Weight,Display Size,Pixel Density,Clock-speed,Wi-Fi Version,Warranty,Price (Rs),Resolution_X,Resolution_Y,Total_Pixels
Weight,1.000000,0.682908,-0.381739,0.009146,-0.084235,-0.028783,0.092558,-0.156321,-0.196181,-0.184680
Display Size,0.682908,1.000000,-0.398369,0.071375,-0.010957,-0.063907,-0.035349,-0.056939,-0.109195,-0.104142
Pixel Density,-0.381739,-0.398369,1.000000,0.227709,0.335456,0.064661,0.496096,0.932117,0.944164,0.935117
Clock-speed,0.009146,0.071375,0.227709,1.000000,0.449003,0.117917,0.295609,0.268852,0.297097,0.256573
Wi-Fi Version,-0.084235,-0.010957,0.335456,0.449003,1.000000,0.129055,0.401253,0.359500,0.377007,0.325056
Warranty,-0.028783,-0.063907,0.064661,0.117917,0.129055,1.000000,0.192243,0.042974,0.063924,0.041896
Price (Rs),0.092558,-0.035349,0.496096,0.295609,0.401253,0.192243,1.000000,0.516805,0.541515,0.504270
Resolution_X,-0.156321,-0.056939,0.932117,0.268852,0.359500,0.042974,0.516805,1.000000,0.973176,0.972245
Resolution_Y,-0.196181,-0.109195,0.944164,0.297097,0.377007,0.063924,0.541515,0.973176,1.000000,0.980559
Total_Pixels,-0.184680,-0.104142,0.935117,0.256573,0.325056,0.041896,0.504270,0.972245,0.980559,1.000000

In [474]:
df.describe()

,Weight,Display Size,Pixel Density,Clock-speed,Wi-Fi Version,Warranty,Price (Rs),Resolution_X,Resolution_Y,Total_Pixels
count,7061.000000,7061.000000,7061.000000,7061.000000,7061.000000,7061.000000,7061.000000,7061.000000,7061.000000,7.061000e+03
mean,1.796063,15.001997,148.491573,2.744512,5.440306,1.104235,65735.773970,1922.546523,1106.492990,2.200988e+06
std,0.389224,0.965148,30.086398,1.216221,0.620254,0.389174,31289.756645,333.150659,227.363489,9.448308e+05
min,0.560000,10.100000,83.000000,0.000000,4.000000,1.000000,9689.000000,720.000000,720.000000,7.776000e+05
25%,1.510000,14.000000,141.000000,2.000000,5.000000,1.000000,40490.000000,1920.000000,1080.000000,2.073600e+06
50%,1.750000,15.600000,141.000000,3.000000,5.000000,1.000000,59990.000000,1920.000000,1080.000000,2.073600e+06
75%,2.080000,15.600000,157.000000,4.000000,6.000000,1.000000,83750.000000,1920.000000,1080.000000,2.073600e+06
max,5.500000,18.400000,338.000000,5.000000,7.000000,3.000000,150000.000000,3840.000000,2400.000000,9.216000e+06

In [475]:
df.sample(3)

,Brand,Model,Weight,Operating System,Display Size,Pixel Density,Display Touchscreen,Clock-speed,Capacity,RAM Type,...,Weight_Category,Resolution_X,Resolution_Y,GPU_Brand,GPU_Tier,CPU_Brand,CPU_Category,Total_Pixels,Screen_Category,PPI_Category
7893,Lenovo,E15 (20TDS0G500),1.70,Windows 10,15.6,141,No,4,8 GB,DDR4,...,Light,1920,1080,NVIDIA,Basic Dedicated,Intel,i5-1Gen,2073600,Medium,Medium
5456,HP,15-dk0050TX (7LH08PA),2.25,Windows 10,15.6,141,No,2,8 GB,DDR4,...,Normal,1920,1080,NVIDIA,Entry Gaming,Intel,i7-9Gen,2073600,Medium,Medium
8014,Lenovo,T490 (20RYS0A000),1.55,Windows 10,14.0,157,No,1,16 GB,DDR4,...,Light,1920,1080,Intel,Integrated,Intel,i7-10Gen,2073600,Medium,Medium

In [476]:
df.columns

Index(['Brand', 'Model', 'Weight', 'Operating System', 'Display Size',
       'Pixel Density', 'Display Touchscreen', 'Clock-speed', 'Capacity',
       'RAM Type', 'SSD Capacity', 'Battery Type', 'Wi-Fi Version', 'Warranty',
       'Price (Rs)', 'Weight_Category', 'Resolution_X', 'Resolution_Y',
       'GPU_Brand', 'GPU_Tier', 'CPU_Brand', 'CPU_Category', 'Total_Pixels',
       'Screen_Category', 'PPI_Category'],
      dtype='str')